### PR TITLE
Add twig extension

### PR DESCRIPTION
**Pull request by YussufSassi**
Thie extension contains:
- Syntax highlighting
- Language server (intellisense)
for the twig templating language.

### CODE REVIEW

**Comment by YussufSassi** [comment]
@cla-bot check

**Comment by williamdes** [comment]
Replaces  #486?

**Comment by YussufSassi** [comment]
Yes, it basically builds upon that extension. It just adds a language server bascially.

**Comment by maxdeviant** [comment]
@YussufSassi Could you update to your `extension.toml` to use just `twig` for the `id` and `Twig` for the name?

https://github.com/YussufSassi/zed-twig/blob/c7df17714b7badeb361df695eaf2e955ec75ae32/extension.toml#L1-L2

**Comment by YussufSassi** [comment]
@maxdeviant Done.

**Comment by maxdeviant** [comment]
@YussufSassi Thank you!

**Comment by shornuk** [comment]
Installed today, but doesn't seem to auto complete, is that right? 

For example I can't type `for` and then tab to get a for loop?

**Pull request merged**
