### PR TITLE
Add COBOL extension

### PR DESCRIPTION
**Pull request by willswire**
This PR adds initial tree-sitter support for COBOL

- Closes: #132
- See also: #585

### CODE REVIEW

**Comment by notpeter** [comment]
You're missing the actual submodule directory in this branch.
You can add with:
```
git submodule add https://github.com/willswire/zed-cobol extensions/cobol
git add extensions/cobol
git commit -m "Add submodule"
git push
```

In the future, if you commit your changes to a branch other than main (e.g. `willswire:something` instead of `willswire:main`) and check the "Allow maintainers to make changes" we can help edit the PR branch directly.

**Comment by willswire** [comment]
@notpeter whoops! thanks for catching that. 

i'll be sure to open future PRs from non-main branches and enable maintainer access!

**Comment by notpeter** [comment]
Does this extension work for you?
When I attempt to run "Install Dev Extension" your repo it does not succeed.
```
2024-12-18T09:54:55.874369-05:00 [INFO] compiling grammar cobol for extension /Users/peter/source/zed-cobol
2024-12-18T09:54:55.874766-05:00 [INFO] checking out cobol parser
2024-12-18T09:54:55.915161-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
2024-12-18T09:54:56.177123-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
2024-12-18T09:54:56.277534-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
2024-12-18T09:54:57.26128-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
2024-12-18T09:54:57.362466-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
2024-12-18T09:54:57.393137-05:00 [INFO] compiling cobol parser
2024-12-18T09:54:57.462856-05:00 [INFO] building git repository, `.git` path in the worktree: "/Users/peter/source/zed-cobol/grammars/cobol/.git"
```
But it never finishes.

I haven't dug into it further, but wanted to confirm: did you actually test this?

**Comment by willswire** [comment]
Hey, thanks for your patience! I revisited this and made a few adjustments to address the issue you encountered. It’s now building and installing successfully on my end.

Let me know if you run into any more problems, and I’ll be happy to dig in further!

**Comment by notpeter** [comment]
Thanks! And congratulations on you first Zed Extension!

**Pull request merged**
