### PR TITLE
Add Biome extension

### PR DESCRIPTION
**Pull request by luckydye**
Adds support for the Biome Language Server. (https://github.com/zed-industries/extensions/issues/388)

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Thanks for opening this @luckydye!

Would you mind filling out the `authors` field for the extension? https://github.com/biomejs/biome-zed/blob/a3eda2789ca75c40e613d9c905671cd31d2b2ff5/extension.toml#L6

**Comment by luckydye** [comment]
My bad, I changed the url..

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Comment by quinncomendant** [comment]
Thanks for this, @luckydye! I’m really excited to have Biome in Zed.

Quick question about how this was implemented: After installing the Biome Zed extension, is it necessary to set any configuration to disable ESLint and Prettier, since their functionality overlaps with Biome? I’m worried they might both be running at the same time, creating conflicts.

**Comment by luckydye** [comment]
@quinncomendant In my oppinion Zed still lacks a little bit there.
As far as I know, the only solution is the formatter config field to configure the behaviour. 

https://zed.dev/docs/reference/all-settings#formatter

Linting can be used side-by-side.

**Pull request merged**
