### PR TITLE
Bump: The Dark Side to 0.2.2

### PR DESCRIPTION
**Pull request by Imgkl**

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Hey @Imgkl, there are changes to other submodules in this PR - you'll have to revert those and just update your submodule, as well as bump the version number in the `extensions.toml` file.

**Comment by Imgkl** [comment]
@JosephTLyons Not sure how I screwed this up 🙈. 

I'll update the PR with just my changes.

**Comment by JosephTLyons** [comment]
Also, you'll need to bump the version in your extension here:

- https://github.com/Imgkl/the-dark-side/blob/d72ac5ae79ec72525f13727550dad371dcd3c508/extension.json#L3

**Comment by JosephTLyons** [comment]
> @JosephTLyons Not sure how I screwed this up 🙈.
> 
> I'll update the PR with just my changes.

No worries, I've had to fiddle around a bunch, fighting the submodules a bit myself.

**Pull request closed without merging**
