### PR TITLE
Add brook-code theme

### PR DESCRIPTION
**Pull request by nyomansunima**
Adding a new theme extension for Zed editor. The extension called "brook-code-theme"

- [x] Passed test
- [x] Added submodules 
- [x] Update the extension.toml file
- [x] Sorting

### CODE REVIEW

**Comment by nyomansunima** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Can you sort the .gitmodules?

In the future, if you check the "allow maintainers to commit changes to my branch" I could've done the fix up.

**Comment by nyomansunima** [comment]
I've been running the "sort-extensions" scripts on my local machine; however, it's getting an error. I use "bun" on my local machine and have no pnpm installed.

**Comment by nyomansunima** [comment]
> Can you sort the .gitmodules?
> 
> In the future, if you check the "allow maintainers to commit changes to my branch" I could've done the fix up.

Everything ok now!!

**Comment by notpeter** [comment]
Thanks! And congrats on your first Zed theme extension!

It was failing on trailing whitespace on the empty line before:
Screenshot 2024-11-27 at 23 58 55

I submitted a fix upstream:
- https://github.com/raravel/git-submodule-js/pull/1

**Comment by nyomansunima** [comment]
Thanks you man

**Pull request merged**
