### PR TITLE
Add extension for the BQN language

### PR DESCRIPTION
**Pull request by DavidZwitser**
[BQN](https://mlochbaum.github.io/BQN/), while relatively niche, is an amazing language, and Zed deserves support for it.
I've implemented all the features Zed has currently. The [readme](https://github.com/DavidZwitser/zed-bqn/blob/main/README.md) describes the decisions.

### CODE REVIEW

**Comment by maxdeviant** [comment]
Thanks @DavidZwitser!

We'll need to change the extension ID in the `extension.toml` to be all lowercase: https://github.com/DavidZwitser/zed-bqn/blob/f4fd839564e8b0e37fe7bc99280d431e1f075ea2/extension.toml#L1

```diff
- id = "BQN"
+ id = "bqn"
```

**Comment by DavidZwitser** [comment]
@maxdeviant my latest commit has a lowercase ID. Any further action needed?

**Comment by DavidZwitser** [comment]
@cla-bot check

**Comment by DavidZwitser** [comment]
@maxdeviant should be fixed now :) (sorry this is my first PR ever)

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
