### PR TITLE
Add Discord presence extension

### PR DESCRIPTION
**Pull request by xhyrom**
Closes https://github.com/zed-industries/extensions/issues/499

GitHub repository: https://github.com/xhyrom/zed-discord-presence

It's done by LSP right now but once Zed gets normal extension support i'll rewrite it :+1:

### CODE REVIEW

**Comment by xhyrom** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@xhyrom Before we go accepting this into the registry, could you say a bit more about how the Discord auth works for the Discord rich presence language server?

**Comment by xhyrom** [comment]
> @xhyrom Before we go accepting this into the registry, could you say a bit more about how the Discord auth works for the Discord rich presence language server?

I'm using https://github.com/vionya/discord-rich-presence which is a pretty nice library for it. You can check the code if you want. It just searches for discord ipc path and connects to it.

**Comment by maxdeviant** [comment]
> > @xhyrom Before we go accepting this into the registry, could you say a bit more about how the Discord auth works for the Discord rich presence language server?
> 
> I'm using https://github.com/vionya/discord-rich-presence which is a pretty nice library for it. You can check the code if you want. It just searches for discord ipc path and connects to it.

I see, so it's just communicating with the local Discord instance over IPC?

I think that assuages my concerns around security 🙂

**Comment by maxdeviant** [comment]
@xhyrom Could you change the extension ID to be `discord-presence` instead of `discord_presence`? We don't allow underscores in extension IDs.

**Comment by xhyrom** [comment]
> @xhyrom Could you change the extension ID to be `discord-presence` instead of `discord_presence`? We don't allow underscores in extension IDs.

fixed

**Comment by maxdeviant** [comment]
> > @xhyrom Could you change the extension ID to be `discord-presence` instead of `discord_presence`? We don't allow underscores in extension IDs.
> 
> fixed

Can you update here as well? https://github.com/zed-industries/extensions/pull/1217/files#diff-724e5177a66640ebdc9d051879ac354bbfd595c1b4d039bab887600964bb2023R231

Unfortunately GitHub won't let me push to this branch since the PR was created from a GitHub organization 😢

**Comment by xhyrom** [comment]
done :D

**Comment by maxdeviant** [comment]
> done :D

@xhyrom I think we're almost there! Looks like the two version numbers don't align right now.

**Comment by xhyrom** [comment]
> > done :D
> 
> @xhyrom I think we're almost there! Looks like the two version numbers don't align right now.

You're right, sorry 😅😃

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
