### PR TITLE
Add extension for Fiberplane Studio

### PR DESCRIPTION
**Pull request by keturiosakys**
Referenced [here](https://x.com/_laurynas/status/1829511925077811289)

This extension allows querying traces stored in the local [Fiberplane Studio](https://fiberplane.com) in the Assistant panel.

### CODE REVIEW

**Comment by keturiosakys** [comment]
The CI issue seems to be unrelated to this package  - anyone from Zed team could advise on how to move this forward?

**Comment by maxdeviant** [comment]
> The CI issue seems to be unrelated to this package - anyone from Zed team could advise on how to move this forward?

The branch was out-of-date with `main`. Just needed it merged in.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Comment by keturiosakys** [comment]
yay thanks!

**Pull request merged**
