### PR TITLE
Add GROQ

### PR DESCRIPTION
**Pull request by juice49**
This branch adds support for [the GROQ language](https://sanity-io.github.io/GROQ/).

### CODE REVIEW

**Comment by juice49** [comment]
@cla-bot check

**Comment by juice49** [comment]
I’m sorry! I messed up the path I added. I’ll follow up with a fix ASAP.

**Comment by juice49** [comment]
The submodule should be fixed now. Sorry about that.

**Comment by maxdeviant** [comment]
> The submodule should be fixed now. Sorry about that.

No worries, thanks for submitting this!

**Pull request merged**
