### PR TITLE
Add Jinja2 extension

### PR DESCRIPTION
**Pull request by ArcherHume**
Adds syntax highlighting and indentation to Jinja2 templates.

Extension repo: https://github.com/ArcherHume/jinja2-support

### CODE REVIEW

**Comment by ArcherHume** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Thanks for the PR!

You'll need to remove the `grammars` directory from your extension repo and add it to `.gitignore`.

**Comment by ArcherHume** [comment]
> Thanks for the PR!
> 
> You'll need to remove the `grammars` directory from your extension repo and add it to `.gitignore`.

Apologies for that, was in a rush! Done now :)

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
