### PR TITLE
Add ruff lsp for python

### PR DESCRIPTION
**Pull request by rodneyosodo**
Add https://github.com/astral-sh/ruff

### CODE REVIEW

**Comment by rodneyosodo** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
Hey @rodneyosodo, thanks for putting this together!

We're actually working on our own Ruff extension at the moment in https://github.com/zed-industries/zed/pull/14198.

**Comment by rodneyosodo** [comment]
@maxdeviant what should be the way forward?

**Comment by maxdeviant** [comment]
The Ruff extension was published in https://github.com/zed-industries/extensions/pull/1101.

**Pull request closed without merging**
