### PR TITLE
Add Swift support

### PR DESCRIPTION
**Pull request by samuser107**

### CODE REVIEW

**Comment by Moshyfawn** [comment]
In order to add your extension repo as a submodule to the extensions repo, please run the following command in the `extensions` folder:
 
```bash
git submodule add https://github.com/samuser107/zed-swift-extension
```

**Comment by samuser107** [comment]
> In order to add your extension repo as a submodule to the extensions repo, please run the following command in the `extensions` folder:
> 
> ```shell
> git submodule add https://github.com/samuser107/zed-swift-extension
> ```

fixed

**Comment by Moshyfawn** [comment]
> > In order to add your extension repo as a submodule to the extensions repo, please run the following command in the `extensions` folder:
> > ```shell
> > git submodule add https://github.com/samuser107/zed-swift-extension
> > ```
> 
> fixed

The submodule should be located **inside the `extensions` folder**, not at the root of the `extensions` repository. Currently, it is located at the root.

image

- To adhere to repo standards, consider adding a concise path with the name of the language your extension supports _(`swift`)_.

```bash
git submodule add https://github.com/samuser107/zed-swift-extension swift
```

**Comment by samuser107** [comment]
sorry for the time lost!

**Comment by samuser107** [comment]
Hi, is there somthing to fix to merge this PR?

**Comment by maxdeviant** [comment]
@samuser107 Thanks for putting this together!

**Pull request merged**
