### PR TITLE
Add SCSS extension

### PR DESCRIPTION
**Pull request by bajrangCoder**
Added scss language support for Zed(https://github.com/zed-industries/zed/issues/5356)

Note: I have not found any language server for scss yet :(

### CODE REVIEW

**Comment by noClaps** [comment]
The [VSCode Language Server for CSS](https://github.com/microsoft/vscode-css-languageservice) also has support for SCSS, so you should be able to use that.

**Comment by bajrangCoder** [comment]
> The [VSCode Language Server for CSS](https://github.com/microsoft/vscode-css-languageservice) also has support for SCSS, so you should be able to use that.

Then I thought not to add LSP through extension because LSP for css is already built in inside zed so user can configure that for scss too(I'm not sure that it's possible or not)

**Comment by maxdeviant** [comment]
@bajrangCoder Thank you!

**Comment by Otterpocket** [comment]
@bajrangCoder ⭐️

**Comment by amaanq** [comment]
thanks for using the ts-grammar org's grammar! glad our org is benefitting users downstream 😁

**Comment by cseelus** [comment]
Thank you!

Does it support `.sass` files (indented syntax) too?

**Comment by bajrangCoder** [comment]
> Thank you!
> 
> Does it support `.sass` files (indented syntax) too?

No

**Comment by cseelus** [comment]
Gotcha, found [this issue on the projects repo](https://github.com/bajrangCoder/zed-scss/issues/3) and the information that this will be a separate extionsion.

**Pull request merged**
