### PR TITLE
Add Sublime Mariana theme

### PR DESCRIPTION
**Pull request by hnatiukr**
Theme, that imitates Sublime Text 4's Mariana theme.

The Mariana color scheme is known for its cool, muted tones that provide a soothing yet vibrant coding environment, making it easy on the eyes during long coding sessions. This theme avoids the use of _cursive or italic_ styles, ensuring a consistent and clean look across all text elements for enhanced readability and focus.

There are two distinct variations: `Sublime Mariana` and Sublime Breakers. Theme variation closely mirrors the original, offering a cool, muted color scheme that’s easy on the eyes.

mariana-zed

> [!NOTE]  
> I’m aware that a [similar theme](https://github.com/biaqat/mariana-theme-zed/tree/f5a79b6a20628a155c339d19e43a31719e0c7636) already exists, but this version offers some key differences. Notably, it contains only two color schemas and uses only the normal text style, with no italic or bold elements, to provide a clean and uniform appearance throughout. If you decide to decline this PR due to the similar existing theme, no problem—just wanted to share an alternative version!

### CODE REVIEW

**Comment by hnatiukr** [comment]
@cla-bot check

**Comment by jackTabsCode** [comment]
I just tried it out, and this theme looks a lot more faithful to the colors of the original than the existing extension! Nice work

**Comment by maxdeviant** [comment]
@blaqat I'd be curious to get your take here as the author of the existing Mariana theme.

I think there is room to have a theme that is true to the original Sublime one, if the divergence in your version of Mariana was an intentional one.

**Comment by blaqat** [comment]
> @blaqat I'd be curious to get your take here as the author of the existing Mariana theme.

This is perfect! I had made the 'Mariana Sublime' variant in mine specifically for people who were requesting more similarities to the original. This one is much better at doing that. 

My original version was intentionally different / biased since it took elements I preferred from Mariana Pro (Vscode) and Juliana (nvim scheme). I also wouldn't mind renaming mine since mines more of a variation.

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
