### PR TITLE
Add Hivacruz theme

### PR DESCRIPTION
**Pull request by kinoute**

### CODE REVIEW

**Comment by kinoute** [comment]
@cla-bot check

**Comment by notpeter** [comment]
You're missing the actual directory containing the submodule (`extensions/zed-hivacruz-theme`).

Also in the future if you make your changes on a branch of your fork (instead of on main) and check the box "Allow Maintainers to push commits" I would've been able to just fix it.

**Comment by kinoute** [comment]
@notpeter Sorry, it was a very late PR! It should be OK now.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
