### PR TITLE
Add nyxvamp-theme

### PR DESCRIPTION
**Pull request by zoedsoupe**
nyxvamp theme

### CODE REVIEW

**Comment by notpeter** [comment]
Thanks! And congrats on your first Zed theme! 🥳

**Comment by notpeter** [comment]
Hi @zoedsoupe,

We require contributors to sign the Zed Contributor License Agreement: https://zed.dev/cla

My apologies for not catching this before the merge, normally the `cla-bot` Github bot would've added a comment here and added a failed check, but that service is currently experiencing an outage.

Would you please go to https://zed.dev/cla and scroll to the bottom and sign.

Thanks.

**Comment by zoedsoupe** [comment]
hey, no problem at all, i noticed that the bot didn't comment anything but got unsure on what to do exactly!

i'll be signing it

**Comment by zoedsoupe** [comment]
done, just successfully signed

**Comment by notpeter** [comment]
It the absence of clabot automation I manually confirmed that you've signed the cla.
Thanks.

**Pull request merged**
