### PR TITLE
Add LSP support for GDScript

### PR DESCRIPTION
**Pull request by grndctrl**
Thank you @moomerman for the LSP implementation.

### CODE REVIEW

**Comment by grndctrl** [comment]
Strange, it appears to be failing on code that hasn't changed. Or am I reading this wrong?

**Comment by maxdeviant** [comment]
> Strange, it appears to be failing on code that hasn't changed. Or am I reading this wrong?
> 
> EDIT: @maxdeviant Since it fails on the version bump, is this something I should omit?

It looks this is an existing problem with one of the included queries that wasn’t caught before:

```
[2024-04-20T14:36:09Z INFO  zed_extension] loaded grammar gdscript
Error: Query error at 5:7. Impossible pattern:
(call (name) @name) @reference.call
      ^
```

Back when the GDScript extension was initially added we just bundled the grammars and so long as they compiled to Wasm we called it a day.

Now the publishing process is more sophisticated and attempts to load the grammar and queries after the grammar is built, and that has uncovered a problem with the queries.

**Comment by grndctrl** [comment]
Fixed the tags, all is good now

**Comment by maxdeviant** [comment]
> Fixed the tags, all is good now

Awesome!

**Pull request merged**
