### PR TITLE
Add Adech Theme extension

### PR DESCRIPTION
**Pull request by adechlien**
Adech Theme extension added as a new Extension for the Editor.

### CODE REVIEW

**Comment by adechlien** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@adechlien Thanks for the PR!

In your extension repo could you move the `adech.json` file into a `themes` directory?

Otherwise it won't get picked up by the extension as a theme.

**Comment by adechlien** [comment]
adech.json moved to themes/

**Review by xtrasmal — APPROVED** [review]

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
