### PR TITLE
Add Gruvbox-ish

### PR DESCRIPTION
**Pull request by LeoDog896**
adds the [gruvbox-ish](https://github.com/LeoDog896/zed-gruvbox-ish) theme ([original](https://github.com/graceful-potato/gruvbox-ish)).

**Note**: I have not explicitly licensed the previous repository. I've contacted the author of `gruvbox-ish` by email, where they said "Of course you can port/modify or do whatever you want with it." If there's some extra requirement for licensing, I can ask for explicit licensing 👍

### CODE REVIEW

**Comment by LeoDog896** [comment]
@cla-bot check

**Comment by morgoth** [comment]
@LeoDog896 There is a builtin gruvbox theme in zed editor.
Maybe it would be possible to port the improvements directly there?
I'm not familiar with changes/content, so not sure if it's easy and it won't break anything else, but would be cool to have solid gruvbox theme out of the box.

**Comment by LeoDog896** [comment]
I could, though that doesn't seem appropriate given the themes changes and relative unpopularity in vscode - this theming extension only has 8 thousand downloads on VSCode.

**Comment by khipp** [comment]
> @LeoDog896 There is a builtin gruvbox theme in zed editor. Maybe it would be possible to port the improvements directly there? I'm not familiar with changes/content, so not sure if it's easy and it won't break anything else, but would be cool to have solid gruvbox theme out of the box.

There was a similar discussion when the Rosé Pine theme was added. The official stance was not to change the built-in themes but to add an extension: https://github.com/zed-industries/zed/issues/9151#issuecomment-1988541178

**Comment by morgoth** [comment]
Thank you for checking

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you update the ID in your `extension.toml` to be just `gruvbox-ish` instead of `zed-gruvbox-ish`?

https://github.com/LeoDog896/zed-gruvbox-ish/blob/e8bda4473ef8a5057c409b4799f0d71dcf6ab93c/extension.toml#L1

**Comment by LeoDog896** [comment]
> Thanks for the PR!
> 
> Could you update the ID in your `extension.toml` to be just `gruvbox-ish` instead of `zed-gruvbox-ish`?
> 
> https://github.com/LeoDog896/zed-gruvbox-ish/blob/e8bda4473ef8a5057c409b4799f0d71dcf6ab93c/extension.toml#L1

[👍](https://github.com/LeoDog896/zed-gruvbox-ish/commit/13ade393632d548cded9b5883585e2dd92efe7b6)

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
