### PR TITLE
Add New Darcula Theme Extension

### PR DESCRIPTION
**Pull request by e-simpson**
Changed:
- `extensions.toml`
- `.gitmodules`

Added:
- `extensions/new-darcula-z` submodule

Screenshot 2024-02-23 at 8 21 01 PM

### CODE REVIEW

**Comment by e-simpson** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@e-simpson Looks like there's a syntax error in the theme file.

Once that's resolved I think this will be good go!

**Comment by e-simpson** [comment]
@maxdeviant thanks for checking on that. Fixed and bumped version.

**Comment by e-simpson** [comment]
Updating submodule..

**Comment by e-simpson** [comment]
Thanks for that @maxdeviant. You're too quick! 😄

**Comment by maxdeviant** [comment]
@e-simpson Thank you for making the theme 😄

**Pull request merged**
