### PR TITLE
Add bitbake extension

### PR DESCRIPTION
**Pull request by anikinmd**
Bitbake language support (Requested at #727)
Repository: https://github.com/anikinmd/zed_bitbake

Support for Bitbake syntax.

- Tree Sitter: [tree-sitter-bitbake](https://github.com/tree-sitter-grammars/tree-sitter-bitbake)
- Language Server: [language-server-bitbake](https://github.com/yoctoproject/vscode-bitbake)

### CODE REVIEW

**Comment by anikinmd** [comment]
@cla-bot check

**Comment by anikinmd** [comment]
I don't understand what's the problem with CI
What should I fix to pass it?

**Comment by maxdeviant** [comment]
> I don't understand what's the problem with CI What should I fix to pass it?

The branch was out-of-date with `main`, so it was picking up changes to unrelated extensions.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
