### PR TITLE
Add env support

### LINKED ISSUE #159: Env
### Check for existing issues

- [X] Completed

### Describe the feature

it would be nice to have some basic syntax highlighting for .env files

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### LINKED ISSUE #776: Syntax recognition .conf
### Check for existing issues

- [X] Completed

### Misc notes

Vscode:
Screenshot 2024-05-22 alle 22 01 05

Zed:

Screenshot 2024-05-22 alle 22 00 57

### PR DESCRIPTION
**Pull request by zarifpour**
Closes #159 and closes #776

### CODE REVIEW

**Comment by zarifpour** [comment]
This is it. You can add issues for better support.

CleanShot_2024-07-12_10 39 11_Zed_001408@2x
CleanShot_2024-07-12_10 39 17_Zed_001410@2x

**Comment by zarifpour** [comment]
Yes, I just need to update [tree-sitter-dotenv](https://github.com/zarifpour/tree-sitter-dotenv) to detect the tokens and add additional elements to `highlights.scm`

**Comment by zarifpour** [comment]
I think this is sufficient for v0.0.1, create issues on the [repo](https://github.com/zarifpour/zed-env) and I'll get around to adding it later when I have time.

**Comment by zarifpour** [comment]
@Angelk90 updated to the following:

CleanShot_2024-07-12_17 13 04_Zed_001418@2x

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
