### PR TITLE
Add cosmos theme

### PR DESCRIPTION
**Pull request by nauvalazhar**
Preview:

image

### CODE REVIEW

**Comment by nauvalazhar** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@nauvalazhar Thank you!

**Comment by SergoGansta777** [comment]
@nauvalazhar This looks marvelous! Could you add an italic version?

**Comment by nauvalazhar** [comment]
@SergoGansta777 I don't think Zed supported it at the moment.

**Comment by SergoGansta777** [comment]
@nauvalazhar As far as I understand the catppuccin theme supports

**Pull request merged**
