### PR TITLE
Add markdown-oxide language server

### PR DESCRIPTION
**Pull request by Feel-ix-343**

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
It looks like the submodule itself needs to be added to the git repo.

**Comment by maxdeviant** [comment]
> It looks like the submodule itself needs to be added to the git repo.

I added the submodule in the latest commit.

**Comment by Feel-ix-343** [comment]
The other thing is that the extension does not automatically download the language server. The user can simply install through cargo. 

The extension is too pre-beta imo to have binaries, so the alternative would be a cargo install through the extension. This however would be a more complex installation than the regular lsp extension. Also, either the latest commit or latest tag should be installed - there would be frequent updates. What do you make of this @maxbrunsfeld ? How would the extension manage the installation or should it? (Its quite common in neovim for a LS to be installed from a normal package manager)

**Comment by maxdeviant** [comment]
> The other thing is that the extension does not automatically download the language server. The user can simply install through cargo.
> 
> The extension is too pre-beta imo to have binaries, so the alternative would be a cargo install through the extension. This however would be a more complex installation than the regular lsp extension. Also, either the latest commit or latest tag should be installed - there would be frequent updates. What do you make of this @maxdeviant ? How would the extension manage the installation or should it? (Its quite common in neovim for a LS to be installed from a normal package manager)

For now I think we can expect the user to have it installed already, and report an error if we can't find it.

Here's how we do something similar in the Uiua extension: https://github.com/zed-industries/zed/blob/5361a4d72dfe8f286581896e9aa7feb232672493/extensions/uiua/src/uiua.rs#L15-L17

**Comment by Feel-ix-343** [comment]
I'll add that

**Comment by Feel-ix-343** [comment]
Is there a way to show the error message in the UI?

**Comment by Feel-ix-343** [comment]
I updated the extension. Do you need to update submodules on here now?

**Comment by Feel-ix-343** [comment]
> Not currently, but we'll probably add something like that in the future.

I can help! I assume the LanguageServerInstallStatus::Failed(...) would be used for the UI right?

**Comment by Feel-ix-343** [comment]
Beyond that, I think this is ready to merge

**Comment by maxdeviant** [comment]
@Feel-ix-343 Thanks!

**Comment by Feel-ix-343** [comment]
@maxdeviant how are extensions updated? I just pushed a commit to the repo

**Pull request merged**
