### PR TITLE
Update XML to v0.0.7

### PR DESCRIPTION
**Pull request by sweetppro**
remove hard coded path extensions in favor of first_line_pattern regex

### CODE REVIEW

**Comment by notpeter** [comment]
```
first_line_pattern = '^<.*xml'
```

Is there a reason you're not just using `<\? *xml` - Are there other possibilities for valid XML headers besides which you are trying to match?
```
<?xml 
<? xml
<?        xml
```

**Comment by sweetppro** [comment]
Xliff files for example can use something like:
`<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">`

**Comment by notpeter** [comment]
FYI I added a little bit of official docs for this too.
So if your regex isn't working for folks they can just add their own extensions.
https://zed.dev/docs/languages/xml

**Comment by sweetppro** [comment]
@notpeter when will the update be live in the gallery?

image

**Pull request merged**
