### PR TITLE
Add Nord theme

### PR DESCRIPTION
**Pull request by mikasius**
Added Nord dark theme for Zed

### CODE REVIEW

**Comment by mikasius** [comment]
@cla-bot check

**Comment by mikasius** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
Thanks for the submission, @mikasius!

In your extension repo the theme needs to be moved into a `themes/` subdirectory. So the path would be `themes/nord.json`.

**Review by maxdeviant — CHANGES_REQUESTED** [review]
See my comment about updating the location of the theme in the extension repo.

**Comment by mikasius** [comment]
@maxdeviant thx for the review! Could please check it again?

**Review by maxdeviant — APPROVED** [review]

**Comment by maxdeviant** [comment]
@mikasius Thank you!

**Pull request merged**
