### PR TITLE
Add Relay extension

### PR DESCRIPTION
**Pull request by XiNiHa**
Adds Relay extension

### CODE REVIEW

**Comment by XiNiHa** [comment]
@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by XiNiHa** [comment]
That doesn't look like my fault 😅

**Review by maxdeviant — APPROVED** [review]
Thanks!

And yea, the CI failures were due to this branch falling behind `main`. Just bad to merge `main` into it.

**Pull request merged**
