### PR TITLE
Add Nix extension

### PR DESCRIPTION
**Pull request by hasit**
Add Nix language support.

Screenshot 2024-02-29 at 23 39 42

### CODE REVIEW

**Comment by hasit** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@hasit Thanks!

**Comment by hasit** [comment]
@maxdeviant Thanks for merging it. When would it be available within Zed to install? What does that process look like?

**Comment by hasit** [comment]
I jumped the gun with previous question. I can now see it in the extensions list and I am able to install it now :)

Screenshot 2024-03-01 at 09 29 25

**Comment by VijayakumarRavi** [comment]
Hi @hasit 

I have installed the extension but I’m still not seeing any syntax highlights, Am i missing something ? can you please help ? 

SCR-20240301-txcm

image

**Comment by hasit** [comment]
Hey, @VijayakumarRavi.

Looks like it is doing syntax highlighting. What theme are you using? Try using another perhaps?

**Comment by VijayakumarRavi** [comment]
It worked after changing theme, sorry 🙆‍♂️

**Comment by Moshyfawn** [comment]
Resolves #268

**Pull request merged**
