### PR TITLE
Add Green Monochrome Monitor CRT Phosphor theme

### PR DESCRIPTION
**Pull request by Takk8IS**
📺 This PR adds the Green Monochrome Monitor CRT Phosphor theme for Zed.

### CODE REVIEW

**Comment by Takk8IS** [comment]
Dear @maxdeviant, what happened now? 😟

**Comment by Moshyfawn** [comment]
- See [the structure section](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#extension-structure) for how to provide your extension's config, and what entries are expected there.

- You also [never added your themes repo as a submodule](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#publishing-your-extension) of this repo in the `extensions` subfolder; the `submodule` field in the extensions config should be the path to the submodule, as it's not just the name of your extension.

- If you could sort your `extensions.toml` extension entry alphabetically, that would also be great, thanks!

**Comment by maxdeviant** [comment]
@Takk8IS I noticed your extension has both `extension.json` and `extension.toml`.

We only need `extension.toml`, the `extension.json` is the legacy format.

**Comment by Takk8IS** [comment]
@Moshyfawn @maxdeviant  Ah ok, got it. Thank you for helping me. I'm not used to using PRs, is everything OK and approved now to publish the theme or should I do the procedure again?

**Comment by maxdeviant** [comment]
> @Moshyfawn @maxdeviant Ah ok, got it. Thank you for helping me. I'm not used to using PRs, is everything OK and approved now to publish the theme or should I do the procedure again?

You just need to remove the `extension.json` file from here https://github.com/Takk8IS/green-monochrome-monitor-crt-phosphor-theme-for-zed/blob/main/extension.json and then I can update the submodule and it will be ready to publish.

**Comment by Takk8IS** [comment]
@maxdeviant done =)

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
