### PR TITLE
Add basedpyright extension

### PR DESCRIPTION
**Pull request by m1guer**
- [x] fix the schemas.

### CODE REVIEW

**Comment by m1guer** [comment]
@cla-bot check

**Comment by m1guer** [comment]
lol i forgot to run the submodule command XD

**Comment by m1guer** [comment]
am i doing anything wrong on extension update?
i already updated the submodule.

**Comment by m1guer** [comment]
its fixed now :p

**Comment by m1guer** [comment]
@maxdeviant any update on this review?

**Comment by failable** [comment]
+1

**Comment by rgbkrk** [comment]
Thank you! I'd love to give this a try. CI has started.

**Comment by m1guer** [comment]
why everytime give this error...?

**Comment by m1guer** [comment]
@rgbkrk can you check for me pls?

**Comment by rgbkrk** [comment]
In https://github.com/m1guer/basedpyright-zed/blob/main/extension.toml, change `id = "python"` to `id = "basedpyright"`.

**Comment by m1guer** [comment]
oh, nice fixed! try now.

**Comment by JosephTLyons** [comment]
You'll have to bump the submodule to point to your newest commit in that repo.

**Comment by m1guer** [comment]
maybe i dont have the capabilities to do that.

**Comment by m1guer** [comment]
lets see if works now.

**Comment by m1guer** [comment]
yayyyy

**Pull request merged**
