### PR TITLE
Add short-giraffe-theme extension

### PR DESCRIPTION
**Pull request by Mehdi-Hp**

### CODE REVIEW

**Comment by Mehdi-Hp** [comment]
@cla-bot check

**Comment by Mehdi-Hp** [comment]
@maxdeviant Can't figure out what went wrong

**Comment by maxdeviant** [comment]
> @maxdeviant Can't figure out what went wrong

It looks like the `author` field is missing:

https://github.com/zed-industries/extensions/actions/runs/9272269166/job/25509612076?pr=789#step:11:28

**Comment by maxdeviant** [comment]
> Well, Yeah, but it's there https://github.com/Mehdi-Hp/Short-Giraffe/blob/b14f44bdffc2039706a2af947958e198dc48e645/extension.json

It's trying to load the `vscode.json` theme as a Zed theme, and complaining about the lack of the `author` field there: https://github.com/Mehdi-Hp/Short-Giraffe/blob/b14f44bdffc2039706a2af947958e198dc48e645/themes/vscode.json#L1-L4

Anything in the `themes` directory will be included as a theme when packaging the extension for Zed.

I would recommend creating a separate subdirectory in your repo to keep the Zed extension in.

**Comment by maxdeviant** [comment]
Closing this out due to inactivity.

If you come back to this, feel free to re-open this PR.

**Comment by Mehdi-Hp** [comment]
This should be good to go now

**Comment by maxdeviant** [comment]
@Mehdi-Hp It looks like the extension is using the old `extension.json` format.

Could you update it to use the new `extension.toml` format? https://zed.dev/docs/extensions/developing-extensions#directory-structure-of-a-zed-extension

**Comment by Mehdi-Hp** [comment]
@maxdeviant Thanks for providing the link. Done

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
