### PR TITLE
Add Shell extension

### PR DESCRIPTION
**Pull request by rburmorrison**
Resubmission of #1064 on a dedicated feature branch.

# shell.zed

Repository: https://github.com/rburmorrison/shell.zed

Support for Bash, POSIX Shell, and ZSH.

- Tree Sitter: [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash)
- Language Server: [bash-language-server](https://github.com/bash-lsp/bash-language-server)

## Features

- Smart LSP Detection
  - Auto-detects installed language server
  - Falls back to installed language server if offline
- Syntax Highlighting
  - Adapted from nvim-treesitter
  - Highlights command flags
- Comprehensive Bracket Jumping
- Smart Indentation
- Linting and Formatting (when dependencies are installed)

### CODE REVIEW

**Comment by maxdeviant** [comment]
Thanks for putting this together, @rburmorrison!

One thing to note is that Zed already has support for shell, bash, and zsh built-in using the bash grammar:

https://github.com/zed-industries/zed/blob/272be98ec854b0cd240fe392101cf02a207c29df/crates/languages/src/bash/config.toml

There's also the `basher` extension (https://github.com/d1y/bash.zed) which provides a Bash language server.

Does this extension add anything that isn't covered by either of those?

**Comment by rburmorrison** [comment]
@maxdeviant 

Hey there! Yeah, I've made several improvements that I think separate this from the base support and Basher.

For one, I work offline quite a lot, and the Basher plugin doesn't take into account if the `bash-language-server` is already installed or not. My plugin detects if it does and uses that without reaching out to the internet. It also falls back to a previous automatically-installed version if it detects that it can't grab the update. Basher just fails to work in those situations and always tries to connect to the internet even if I have something already present, so I can't use it at all. So that's one big improvement.

As for the grammar for shell that's both built-into Zed and in Basher (which I believe use the same queries), I've used a different base and enhanced it quite a bit. The syntax highlighting is more detailed and highlights several nuances that aren't covered in the existing solutions. I've adapted it from the grammar which is a bit more comprehensive with the highlighting.

Some more features that my queries have that the base one doesn't include are:

- Functions are included in the "outline" view (both POSIX-compliant and `function` keyword-prefixed)
- Indentation automatically increments and decrements with certain keywords (the base one doesn't indent at all)
  - Array Contruction
  - Function Bodies
  - Increments after: `then`, `do`, `else`, etc
  - Decrements after: `else`, 'elif `, 'fi', etc
- Comprehensive bracket jumping for more brackets for use with `%` in Vim mode
  - `$((` `))`
  -  `[[` `]]`
  - `<(` `)`
  - And more Bash braces (the base one accounts only for `(`, `[`, and `{`)

There's more improvements such as balanced braces being generated (the base version will do `[[ ]` when typing in `[[` rather than `[[ ]]`, for example) as well.

I think it's awesome that Basher exists and that Zed has built-in support, but I believe this plugin significantly improves the user experience for Shell scripts in Zed from the existing solutions.

**Comment by rburmorrison** [comment]
@maxdeviant 

Hey again, wanted to check in on this since it's been a few weeks.

Is there anything I can clarify or do to get this merged in? It's be great to have this enhanced Shell support in Zed!

I'd also like to offer to push the queries that I've made to Zed's core to enhance the out-of-the-box shell experience as well. Let me know if that would be something that the project would like :)

**Comment by maxdeviant** [comment]
> @maxdeviant
> 
> Hey again, wanted to check in on this since it's been a few weeks.
> 
> Is there anything I can clarify or do to get this merged in? It's be great to have this enhanced Shell support in Zed!
> 
> I'd also like to offer to push the queries that I've made to Zed's core to enhance the out-of-the-box shell experience as well. Let me know if that would be something that the project would like :)

Right now it's not clear to me what this extension offers that is not available in the built-in shell support in Zed and the `basher` extension (which provides a Bash language server).

You mention some improvements that you've made both to how the `bash-language-server` installation works as well as to the queries, but I think these would be better off as contributions to Zed/basher rather than creating another competing extension.

**Comment by GrabbenD** [comment]
I’d like to share a fresh perspective @maxdeviant

Given that an overwhelming majority of Linux distributions rely on Shell Scripting, it's very disheartening to see it treated as a second-class citizen

* **[8 months](https://github.com/d1y/bash.zed/commits/main) of inactivity in the main codebase:**
    - Commonplace [issues](https://github.com/d1y/bash.zed/issues) _(like LSP PATH detection)_ haven't been acknowledged
    - [TODO](https://github.com/d1y/bash.zed/blob/e2be9c584cbf92ad73642e3c2ecde0c8dbe7a024/src/bash.rs#L84) from [initial](https://github.com/zed-industries/zed/pull/9902/files#diff-c9cd407fcd03627905d2690f9d90792f6aa4e6a7b9c9cf392fb249635be04731R84) implamentation never got addressed
    - Maintainer's Github Profile shows [little](https://github.com/d1y?tab=overview) activity in recent months
    - Extension is stuck on [tree-sitter-bash release from March](https://github.com/d1y/bash.zed/blob/main/extension.toml#L17C8-L17C48)
* **Consider that @rburmorrison's code is a comprehensive rewrite rather than an enhancement of the existing extension:**
    - Basher contains merely barebone support for Bash in the first place
    - Shortcomings of Basher are perfectly summed up by the improvements described [above](https://github.com/zed-industries/extensions/pull/1078#issuecomment-2239971489)
    - This PR fills obvious gaps for users coming from VSCode

**This raises the question of whether _denying_ overhauls of existing extensions is counterproductive**:
  - Maintaining a high-quality extensions repository requires active maintainers who can take ownership of the code
  - Restricting submissions from new and talented maintainers solely because similar extensions already exist is discouraging
  - New users get a poor first impression when _prevalent features_ that require third-party extensions remain stale for months

Felt like bringing this up is important considering this exact scenario is bound to happen again sooner or later :slightly_frowning_face:

**Comment by pbsds** [comment]
Considering there are at the time of writing [four different markdown extensions](https://zed.dev/extensions?query=markdown), I don't see the reason why this PR was closed. I would very much love to use this extension over basher, considering that its lack of the "Auto-detects installed language server" is a total blocker on NixOS.

**Comment by rubin55** [comment]
Please re-open this issue, basher is dead and/or ignores a very valid concern (i.e., be able to run your own bash-language-server instead of downloading).

**Pull request closed without merging**
