### PR TITLE
Add Penumbra theme

### LINKED ISSUE #45: Penumbra
### Check for existing issues

- [X] Completed

### Misc notes

Example in Helix editor:

image

### PR DESCRIPTION
**Pull request by jbisits**
Adds a light and dark [penumbra](https://github.com/nealmckee/penumbra) theme. The themes were ported from vs code using the theme importer in zed.

Closes #45

### CODE REVIEW

**Comment by jbisits** [comment]
@cla-bot check

**Comment by jbisits** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
Thanks for opening this @jbisits!

Could you update the name of the theme to just be "Penumbra" or "Penumbra Theme"?

https://github.com/jbisits/penumbra-zed/blob/fad91e5af4981ffaf9769a80a316622f6d55f98c/extension.json#L2

We don't need the "for zed" in the name, since these are all Zed extensions.

**Comment by jbisits** [comment]
> Could you update the name of the theme to just be "Penumbra" or "Penumbra Theme"?
https://github.com/jbisits/penumbra-zed/blob/fad91e5af4981ffaf9769a80a316622f6d55f98c/extension.json#L2
We don't need the "for zed" in the name, since these are all Zed extensions.

Done!

**Comment by maxdeviant** [comment]
@jbisits Thanks!

**Pull request merged**
