### PR TITLE
theme: Add NeoSolarized Zed theme

### PR DESCRIPTION
**Pull request by carlocaione**
Pushing as extension as suggested in https://github.com/zed-industries/zed/pull/7616

### CODE REVIEW

**Comment by carlocaione** [comment]
@maxdeviant not sure how to test this though

**Comment by maxdeviant** [comment]
Thanks for opening this, @carlocaione!

We're still wrapping up some stuff with the extensions, but we'll merge this when we're ready.

> @maxdeviant not sure how to test this though

As long as the theme is working fine we can make sure the extension works on our end (once that part is ready) 😄

**Comment by maxdeviant** [comment]
@carlocaione I opened a PR up on your theme extension repo to update it to the latest expected structure: https://github.com/carlocaione/NeoSolarized.zed/pull/1

**Comment by carlocaione** [comment]
@maxdeviant merged

**Pull request merged**
