### PR TITLE
Replace/Re-Add Odin language extension

### PR DESCRIPTION
**Pull request by rxptr**
Odin Language extension

### CODE REVIEW

**Comment by rxptr** [comment]
@cla-bot check'

**Comment by notpeter** [comment]
Hi @rxptr, I just wanted to let you know there was previously an Odin extension, but I pulled it from the repo here:
- https://github.com/zed-industries/extensions/pull/1661

because the upstream repository went missing and I hadn't heard back from the maintainer.  I don't know how different your extension is from the previous one, but instead of starting fresh I wanted to see if you'd be willing to take over maintaining/modifying the existing extension.  I preserved my local clone here: https://github.com/notpeter/zed-odin but have no interest in maintaining it. It's MIT licensed.

I haven't yet unpublished it from the Zed Extensions, but that was on my todo for this week.

Happy to transfer you the repo if you'd like.
Or if you want a fresh start, that's fine too.
Just thought I'd ask.

**Comment by rxptr** [comment]
Hi @notpeter, the repos are pretty similar, I just use the latest tree-sitter. The reason I did created this was because I couldn't find any in extensions for Odin, I wasn't aware there was one before. Anyways, If it's okay, just merge mine.

**Comment by notpeter** [comment]
I'm happy to merge yours. Yes, you should bump your version to something greater than 0.1.1 (e.g. `0.2.0`).  You'll have to:
1. Edit extension.toml in your repo, commit and push.
2. (a) Edit extensions.toml in this PR (b) checkout the `extensions/odin` submodule to that new commit.

That way the existing users should transition seamlessly.

**Comment by notpeter** [comment]
Thanks! And congrats on publishing your first Zed extension!

**Pull request merged**
