### PR TITLE
Add CUE language extension

### PR DESCRIPTION
**Pull request by jkasky**
Adds CUE language extension. Fixes: #190

This is my first attempt at creating an extension for Zed and tree-sitter queries, feedback greatly appreciated 🙇🏼‍♂️ 

image

image

### CODE REVIEW

**Comment by jkasky** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@jkasky Thanks!

**Comment by yangzhares** [comment]
Is there a way to install this extension in local? Thanks!

**Comment by notpeter** [comment]
@yangzhares Yes.  You can close the [jkasky/zed-cue](https://github.com/jkasky/zed-cue) repo locally and then use "install dev extension" in Zed to build and install it locally.  Here are instructions, but basically it requires installing the correct rust toolchains with rustup.
https://zed.dev/docs/extensions/developing-extensions

It is also available pre-build by opening `zed: extensions` and searching for `cue`:
Screenshot 2025-02-17 at 11 57 44

**Pull request merged**
