### PR TITLE
Update Siri to 0.0.5

### PR DESCRIPTION
**Pull request by perragnar**
Changed theme id to lowercase

### CODE REVIEW

**Comment by maxdeviant** [comment]
Is this different than #849?

**Comment by perragnar** [comment]
It's the same. I just changed the extension id to lowercase.

**Comment by maxdeviant** [comment]
It looks like the current extension submodule is already pointing to https://github.com/perragnar/zed-theme-siri/commit/e53ea36b4e5e8a20f52d3b37aa705643c312d214, so it doesn't seem this PR does anything.

**Comment by perragnar** [comment]
You're right. I hade problems getting things to work yesterday. I'll close the PR.

**Pull request closed without merging**
