### PR TITLE
Update Monospace theme to v0.1.2

### PR DESCRIPTION
**Pull request by Abhinav5383**
Updated the version number from 0.1.1 to 0.1.2

Changes:
- Fixed the attribute color being the same as JSX component tag color

### CODE REVIEW

**Comment by Abhinav5383** [comment]
Can i get some help,
I don't know what's wrong
The version number in the `extensions.toml` matches the number in the submodule's `extension.toml` but it still says version mismatch

the error
```
Error: Incorrect version for extension monospace-theme (Monospace Theme)
Expected version: 0.1.2
Actual version: 0.1.1
```

I have double checked it, the version in both places is `0.1.2`.

*and this 2nd pr for the same thing, i thought the issues was because i opened the last pr after only a few seconds of committing the change in the extension repo but no use, it still fails (closed the last pr)

**Comment by maxdeviant** [comment]
> Can i get some help, I don't know what's wrong The version number in the `extensions.toml` matches the number in the submodule's `extension.toml` but it still says version mismatch
> 
> the error
> 
> ```
> Error: Incorrect version for extension monospace-theme (Monospace Theme)
> Expected version: 0.1.2
> Actual version: 0.1.1
> ```
> 
> I have double checked it, the version in both places is `0.1.2`.
> 
> *and this is 2nd pr for the same thing, i thought the issue was because I opened the last pr after only a few seconds of committing the change in the extension repo but no use, it still fails (closed the last pr)

You need to update the submodule as well: https://github.com/zed-industries/extensions/blob/d28af6e18606c7c00e99ca6c80209e7e67e9168a/AUTHORING_EXTENSIONS.md#updating-an-extension

**Comment by Abhinav5383** [comment]
Ummm, I have the version number updated in the submodule to match the new version
[https://github.com/Abhinav5383/zed-monospace-theme/blob/main/extension.toml](https://github.com/Abhinav5383/zed-monospace-theme/blob/main/extension.toml)

That's what the Updating guide also says, to update the version number in both this repo's extensions.toml and in submodule's extension.toml

**Comment by maxdeviant** [comment]
> Ummm, I have the version number updated in the submodule to match the new version https://github.com/Abhinav5383/zed-monospace-theme/blob/main/extension.toml
> 
> That's what the Updating guide also says, to update the version number in both this repo's extensions.toml and in submodule's extension.toml

You need to also update the submodule reference in this repo to have the commit from your repository with the updated version number.

**Comment by Abhinav5383** [comment]
huh!
finalllyyyyyyyyyyy :)

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
