### PR TITLE
Add Ledger extension

### PR DESCRIPTION
**Pull request by mrkstwrt**

### CODE REVIEW

**Comment by mrkstwrt** [comment]
@cla-bot check

**Comment by mrkstwrt** [comment]
@maxdeviant sorry I've updated the submodule to use https instead

**Review by maxdeviant — DISMISSED** [review]
Thank you!

**Comment by mrkstwrt** [comment]
@maxdeviant should be fixed now, updated the id in my extension to match the `extensions.toml` id

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
