### PR TITLE
Add Cap'n Proto extension

### PR DESCRIPTION
**Pull request by cmackenzie1**
This adds a Cap'n Proto extension to the Zed extension registry.

https://github.com/cmackenzie1/zed-capnp
https://capnproto.org

### CODE REVIEW

**Comment by cmackenzie1** [comment]
@cla-bot check

**Comment by cmackenzie1** [comment]
Reordered the entry in the `.gitmodules` file.

**Comment by cmackenzie1** [comment]
@maxdeviant done!

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Comment by cmackenzie1** [comment]
Thanks for reviewing and merging @maxdeviant. It looks like the publish job failed after merging into main. https://github.com/zed-industries/extensions/actions/runs/8729021921/job/23950097579

**Pull request merged**
