### PR TITLE
Add One Dark Flat theme

### PR DESCRIPTION
**Pull request by 0PandaDEV**
I made a new theme called One Dark Flat as a port of [One Dark Pro](https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme) to Zed

### CODE REVIEW

**Comment by 0PandaDEV** [comment]
@cla-bot check

**Comment by notpeter** [comment]
There's a couple things going on here:
1. You are missing an entry from `extensions.toml`
2. Your .gitmodules is unsorted, fix by running `pnpm sort-extensions` or sorting manually
3. I introduced a git conflict in https://github.com/zed-industries/extensions/pull/1698 (sorry!). You'll want to merge/rebase to `origin/main`

In the future if you create a branch on your fork (named something other than `main`) we can help fix these things by directly committing to your branch.

**Comment by 0PandaDEV** [comment]
@notpeter I fixed all the issues.

**Comment by notpeter** [comment]
Thanks!

**Pull request merged**
