### PR TITLE
Add Material Dark Theme Extension

### PR DESCRIPTION
**Pull request by xerodark**
### Description
This pull request introduces the "Material Dark" theme to the Zed IDE, offering a sleek and modern dark theme that aligns with the Material Design guidelines. The theme is designed to provide a visually appealing and comfortable development environment, especially for developers who prefer dark mode for extended coding sessions.

### Changes
- Added the Material Dark theme as a submodule in the `extensions/material-dark-theme` directory.
- Updated the `extensions.toml` file to include the new Material Dark theme with the following entry:
  ```toml
  [material-dark-theme]
      path = "extensions/my-material-dark-theme"
      version = "1.0.0"
  ```
### Testing
The theme has been tested locally within the Zed IDE to ensure compatibility and a consistent user experience across various file types and programming languages. It adheres to the JSON schema specified at [https://zed.dev/schema/themes/v0.1.0.json](https://zed.dev/schema/themes/v0.1.0.json), ensuring that all theme aspects are correctly applied within the IDE.

### Screenshots
image
image

### Additional Notes
The Material Dark theme aims to enhance the Zed IDE's visual environment while maintaining readability and reducing eye strain during nighttime coding sessions. It's inspired by the principles of Material Design, focusing on usability and aesthetics.

I look forward to any feedback or suggestions for improvement. Thank you for considering this addition to the Zed IDE extensions registry and I'm excited to see how this IDE continues to develop.

### CODE REVIEW

**Comment by xerodark** [comment]
@cla_bot check

**Comment by xerodark** [comment]
@cla_bot check

**Comment by xerodark** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@xerodark Thank you!

**Pull request merged**
