### PR TITLE
Add Night Owl theme

### PR DESCRIPTION
**Pull request by elGusto**
Adds a port of the requested Night Owl theme: https://github.com/zed-industries/extensions/issues/35

image

### CODE REVIEW

**Comment by elGusto** [comment]
@cla-bot check

**Comment by elGusto** [comment]
@cla-bot check

**Comment by elGusto** [comment]
@cla-bot check

**Comment by elGusto** [comment]
Sorry for the multiple checks, I had made commits with another git id...

**Comment by maxdeviant** [comment]
> Sorry for the multiple checks, I had made commits with another git id...

All good!

**Comment by maxdeviant** [comment]
@elGusto Could you update the name and authors in the theme file in your extension repo?

https://github.com/elGusto/night-owlz/blob/78a694dbab552b4a5d3df53ff6a8426b3fc11fa2/themes/NightOwl.json#L3-L4

**Comment by elGusto** [comment]
@maxdeviant done!

**Comment by maxdeviant** [comment]
@elGusto Thank you!

**Pull request merged**
