### PR TITLE
Updates dracula from 0.2.0 to 0.3.0

### PR DESCRIPTION
**Pull request by Otterpocket**

### CODE REVIEW

**Comment by JosephTLyons** [comment]
Thanks!

**Comment by JosephTLyons** [comment]
I just updated from 0.2.0 to 0.3.0, and the difference is dramatic! Looking awesome on my end!

**Comment by JosephTLyons** [comment]
Sorry for derailing this thread, I couldn't find you on social media to tag you, but I highighted this extension in today's extension hightlight tweet!

https://x.com/zeddotdev/status/1768668488485208190?s=20

(Sorry for derailing this thread)

**Comment by Otterpocket** [comment]
> Sorry for derailing this thread, I couldn't find you on social media to tag you, but I highighted this extension in today's extension hightlight tweet!
> 
> https://x.com/zeddotdev/status/1768668488485208190?s=20
> 
> (Sorry for derailing this thread)

Oh that's cool.
Haha, no problem. I'm not on social media. Maybe I should be now I'm famous 🤩

**Pull request merged**
