### PR TITLE
Add Lucid Dream theme

### PR DESCRIPTION
**Pull request by kloudsamurai**
Lucid Dream Dark Theme

1. Semi transparent for use with video wallpaper or other attractive background
2. SurrealDB style color schematic for good contrast

### CODE REVIEW

**Comment by kloudsamurai** [comment]
@cla-bot check

**Comment by kloudsamurai** [comment]
lucid-dream-dark

**Comment by notpeter** [comment]
You have to actually add the directory which contains the gitsubmodule to the git commit not just the `.gitmodules` change.

In the future, if you use a branch instead of `main` on your fork and check the "Allow Maintainers to commit changes" we could help fix-up things like this.

**Comment by notpeter** [comment]
```
Error: IDs in `extensions.toml` and `extension.toml` do not match:

extensions.toml: lucid-dream-theme
 extension.toml: lucid-dream
```
In the future, if your commits are on a branch of your fork instead of main, I could fixup this for you.

**Comment by kloudsamurai** [comment]
thank you. i will in the future and i can only improve vs this attempt ;) fixing now.

**Comment by notpeter** [comment]
Closing as unmerged.  If you would like to try again, please open a new PR (this time ideally on a branch other than main).

**Pull request closed without merging**
