### PR TITLE
Add vscode-dark-modern theme

### PR DESCRIPTION
**Pull request by kcamcam**
This pull request adds a port of Visual Studio Code's [Dark Modern](https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_modern.json) theme to Zed.
- https://github.com/kcamcam/vscode_dark_modern.zed

preview

### CODE REVIEW

**Comment by kcamcam** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@kcamcam It looks like the extension repo is not public.

**Comment by kcamcam** [comment]
thanks for the quick review @maxdeviant. 

Sorry about that, it has been changed to public.

**Comment by maxdeviant** [comment]
@kcamcam Could you update your extension ID to `vscode-dark-modern`?

https://github.com/kcamcam/vscode_dark_modern.zed/blob/92f4b011fda87991ca99fc79dddd1cedbbd1811b/extension.toml#L1

**Comment by kcamcam** [comment]
> @kcamcam Could you update your extension ID to `vscode-dark-modern`?
> 
> 
> 
> https://github.com/kcamcam/vscode_dark_modern.zed/blob/92f4b011fda87991ca99fc79dddd1cedbbd1811b/extension.toml#L1

@maxdeviant that's done ✅

https://github.com/kcamcam/vscode_dark_modern.zed/commit/a60ddde89cf0c3d56d89fb71543f3e4e5ab8b9a5

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
