### PR TITLE
Update zed-sql and zed-log repos (transferred from evrsen to evrensen467)

### PR DESCRIPTION
**Pull request by notpeter**
These repos were transferred to a different account.
From @evrsen to @evrensen467.

When these are merged, update the submodules to match commits on the new repos.

- https://github.com/evrensen467/zed-sql/pull/5
- https://github.com/evrensen467/zed-log/pull/3
- https://github.com/evrensen467/zed-log/pull/4

### CODE REVIEW

**Comment by maxdeviant** [comment]
Looks like these repos got moved again:

- https://github.com/nsdeviex/zed-sql
- https://github.com/nsdeviex/zed-log

**Comment by nsdeviex** [comment]
sorry, I'm going to fix this soon! 😬 but things still work in the meantime right, i.e the repositories are redirected no?

**Comment by nervenes** [comment]
I've updated the repos now!

zed-log link: https://github.com/nervenes/zed-log
zed-log version: ``0.0.6``

zed-sql link: https://github.com/nervenes/zed-sql
zed-sql version: ``1.1.2``

**Comment by nervenes** [comment]
sorry for the inconvenience, won't happen again.

**Comment by notpeter** [comment]
@maxdeviant I accidentally committed these changes directly to main in https://github.com/zed-industries/extensions/commit/3ad3560c55f9e2d1c04ecc2b4986f280189355c6. My apologies.

**Pull request closed without merging**
