### PR TITLE
Update git-firefly to v0.0.3

### PR DESCRIPTION
**Pull request by d1y**
In #649, The PR update new style with extension format(old use .json) and gitignore path_suffixes contains .dockerignore

/cc @eth0net

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@d1y The `grammars/` directory should be added to `.gitignore` when using the `extension.toml` format.

We don't want the grammar repos referenced as submodules.

**Comment by maxdeviant** [comment]
@d1y Could you also remove the `grammars` directory from Git (since it looks like it was committed before `grammars` was added to the `.gitignore`)?

**Comment by d1y** [comment]
> @d1y Could you also remove the `grammars` directory from Git (since it looks like it was committed before `grammars` was added to the `.gitignore`)?

Is that what you mean?

```bash
git rm -r --cached grammars/
git commit --amend --no-edit
git push -f
```

**Comment by maxdeviant** [comment]
> > @d1y Could you also remove the `grammars` directory from Git (since it looks like it was committed before `grammars` was added to the `.gitignore`)?
> 
> Is that what you mean?
> 
> ```shell
> git rm -r --cached grammars/
> git commit --amend --no-edit
> git push -f
> ```

I believe that should work!

But perhaps something more is needed in the case of submodules? Although I think deleting the directory from Git would also remove the submodules in the `grammars/` directory.

**Comment by maxdeviant** [comment]
> Sorry, it took so long. Is it OK now? @maxdeviant

Could you change the `id` in `extension.toml` back to `git-firefly`?

https://github.com/d1y/git_firefly/blob/7f3a8b79641aac2bcd047cec46d357ad54b1c15b/extension.toml#L1

Right now it is `git_firefly`.

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
