### PR TITLE
Add Navi language extension

### PR DESCRIPTION
**Pull request by huacnlee**
https://navi-lang.org

https://github.com/navi-language/zed-navi

## Screenshot

image

### CODE REVIEW

**Comment by huacnlee** [comment]
Can I implementation LSP with extension mode now? And how?

I have written LSP support in Zed source, all things are done.

https://github.com/navi-language/zed-navi/blob/main/src/lib.rs

20240218170833_rec_

**Comment by maxdeviant** [comment]
> Can I implementation LSP with extension mode now? And how?

We are currently working on the ability to add language servers in extensions. Support for this will be coming soon.

**Comment by huacnlee** [comment]
Please merge this extension first, at least the grammar highlighting is useful for now.

I will update it again, when Zed done with the LSP extension support.

**Comment by maxdeviant** [comment]
@huacnlee Thanks!

**Pull request merged**
