### PR TITLE
Add XML extension

### PR DESCRIPTION
**Pull request by sweetppro**

### CODE REVIEW

**Comment by maxdeviant** [comment]
@sweetppro It looks like the XML grammar might need to be updated:

```
Error: Failed to instantiate wasm module: language version 12 is too old for wasm
```

**Comment by sweetppro** [comment]
@maxdeviant how do I go about that

**Comment by maxdeviant** [comment]
> @maxdeviant how do I go about that

It looks like you're already using the latest version of the grammar that's available, so you'll probably need to talk with the maintainer of `tree-sitter-xml` to see about making it support Wasm.

**Comment by sweetppro** [comment]
> > @maxdeviant how do I go about that
> 
> It looks like you're already using the latest version of the grammar that's available, so you'll probably need to talk with the maintainer of `tree-sitter-xml` to see about making it support Wasm.

https://github.com/tree-sitter-grammars/tree-sitter-xml/issues/18#issuecomment-2075551123

**Comment by maxdeviant** [comment]
> > > @maxdeviant how do I go about that
> > 
> > 
> > It looks like you're already using the latest version of the grammar that's available, so you'll probably need to talk with the maintainer of `tree-sitter-xml` to see about making it support Wasm.
> 
> [tree-sitter-grammars/tree-sitter-xml#18 (comment)](https://github.com/tree-sitter-grammars/tree-sitter-xml/issues/18#issuecomment-2075551123)

Oh, I didn't realize there was a `tree-sitter-xml` in the Tree-sitter org.

That's not the one you're using in your extension:

https://github.com/sweetppro/zed-xml/blob/c35cc5edf8779f7a357628e9d3347be4a78093cc/grammars/xml.toml#L1-L2

https://github.com/dorgnarg/tree-sitter-xml

So if you update your extension to use https://github.com/tree-sitter-grammars/tree-sitter-xml then that should address the problem.

**Comment by sweetppro** [comment]
ah,
that was updated in this pull request:
https://github.com/sweetppro/zed-xml/commit/4776e63ad1655bcda531038762b7e4377af25f31

**Comment by maxdeviant** [comment]
> ah, that was updated in this pull request: [sweetppro/zed-xml@4776e63](https://github.com/sweetppro/zed-xml/commit/4776e63ad1655bcda531038762b7e4377af25f31)

Oh, so it's just the submodule that needs to be updated then, since it's still at `c35cc5edf8779f7a357628e9d3347be4a78093cc`.

**Comment by sweetppro** [comment]
ok, it should be updated now :)

**Comment by maxdeviant** [comment]
@sweetppro Thanks!

**Comment by someone13574** [comment]
> @ sweetppro Thanks!

Can the linked issue be closed?

**Pull request merged**
