### PR TITLE
Add catppuccin-blur theme

### PR DESCRIPTION
**Pull request by jenslys**
A fork of the [Catppuccin](https://github.com/catppuccin/zed) that includes 2 custom variants.
Repo: https://github.com/jenslys/zed-catppuccin-blur

##  Preview

Latte Preview

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Can we use a different name for the extension?

Right now it's just "Catppuccin Themes", which is the same as the official Catppuccin extension, which I think is going to cause some confusion:

https://github.com/jenslys/zed-catppuccin-blur/blob/f58a8b5b602c253525822b76be6018c0f596856d/extension.toml#L2

**Comment by maxdeviant** [comment]
> Can we use a different name for the extension?
> 
> Right now it's just "Catppuccin Themes", which is the same as the official Catppuccin extension, which I think is going to cause some confusion:
> 
> https://github.com/jenslys/zed-catppuccin-blur/blob/f58a8b5b602c253525822b76be6018c0f596856d/extension.toml#L2

Alternatively, we could see if the Catppuccin folks would be amenable adding these two theme variants to the main Catppuccin extension.

**Comment by jenslys** [comment]
> Can we use a different name for the extension?
> 
> Right now it's just "Catppuccin Themes", which is the same as the official Catppuccin extension, which I think is going to cause some confusion:
> 
> [jenslys/zed-catppuccin-blur@`f58a8b5`/extension.toml#L2](https://github.com/jenslys/zed-catppuccin-blur/blob/f58a8b5b602c253525822b76be6018c0f596856d/extension.toml#L2)

How about just calling it "Catppuccin Blur"?

Seeing the amount of catppuccin variant forks on vscode, i doubt they will be open to merging the blur variants

**Comment by maxdeviant** [comment]
> > Can we use a different name for the extension?
> > Right now it's just "Catppuccin Themes", which is the same as the official Catppuccin extension, which I think is going to cause some confusion:
> > [jenslys/zed-catppuccin-blur@`f58a8b5`/extension.toml#L2](https://github.com/jenslys/zed-catppuccin-blur/blob/f58a8b5b602c253525822b76be6018c0f596856d/extension.toml#L2)
> 
> How about just calling it "Catppuccin Blur"?
> 
> Seeing the amount of catppuccin variant forks on vscode, i doubt they will be open to merging the blur variants, since i also have other theme changes, besides just making the BG blurry
> 
> image

Yep, "Catppuccin Blur" sounds good!

**Comment by jenslys** [comment]
> > > Can we use a different name for the extension?
> > > Right now it's just "Catppuccin Themes", which is the same as the official Catppuccin extension, which I think is going to cause some confusion:
> > > [jenslys/zed-catppuccin-blur@`f58a8b5`/extension.toml#L2](https://github.com/jenslys/zed-catppuccin-blur/blob/f58a8b5b602c253525822b76be6018c0f596856d/extension.toml#L2)
> > 
> > 
> > How about just calling it "Catppuccin Blur"?
> > Seeing the amount of catppuccin variant forks on vscode, i doubt they will be open to merging the blur variants, since i also have other theme changes, besides just making the BG blurry
> > image
> 
> Yep, "Catppuccin Blur" sounds good!

Updated

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
