### PR TITLE
Add Justfile support

### LINKED ISSUE #156: Justfile
### Check for existing issues

- [X] Completed

### Language

Justfile

### Tree Sitter parser link

https://github.com/IndianBoy42/tree-sitter-just

### Language server link

_No response_

### Misc notes

Similar enough to makefiles to maybe just use make syntax.

### PR DESCRIPTION
**Pull request by jackTabsCode**
Fixes #156

### CODE REVIEW

**Comment by jackTabsCode** [comment]
Not entirely sure why the workflow failed, can anyone point me in the right direction?

**Comment by maxdeviant** [comment]
> Not entirely sure why the workflow failed, can anyone point me in the right direction?

It looks like the Git submodule wasn't committed to the repo.

There is an entry in `.gitmodules`, but we're missing the actual submodule reference at `extensions/just`.

**Comment by jackTabsCode** [comment]
> > Not entirely sure why the workflow failed, can anyone point me in the right direction?
> 
> It looks like the Git submodule wasn't committed to the repo.
> 
> There is an entry in `.gitmodules`, but we're missing the actual submodule reference at `extensions/just`.

I think it should be fixed now? I have very limited experience with submodules.

**Comment by maxdeviant** [comment]
Looks like it's failing now because the version number in the extension's `extension.toml` doesn't match the one listed in `extensions.toml`: https://github.com/jackTabsCode/zed-just/blob/c35a129a1f0f8bdc0e9b7305aea06c7b7b5f3e09/extension.toml#L4

**Comment by jackTabsCode** [comment]
Ok, let's try again?

**Comment by maxdeviant** [comment]
@jackTabsCode Thanks!

**Pull request merged**
