### PR TITLE
Add Ice Ice Bergy theme

### PR DESCRIPTION
**Pull request by jmsdnns**
Similar to Iceberg, but I find it's easier on the eyes. Screenshots available here: https://github.com/jmsdnns/zed-iceicebergy.

### CODE REVIEW

**Comment by jmsdnns** [comment]
Hmm. From what I can tell, the check didn't fail because of my theme. The log output suggests it is something to do with a package called `kanagawa-themes`.

```
Packaging 'iceicebergy'. Version: 0.3.14
Checking out Git submodule at 'extensions/iceicebergy'

Packaging 'kanagawa-themes'. Version: 0.0.1
Checking out Git submodule at 'extensions/kanagawa-themes'
file:///home/runner/work/extensions/extensions/src/package-extensions.js:148
    throw new Error(
          ^

Error: The `extension.json` manifest format has been superseded by `extension.toml`
    at packageExtension (file:///home/runner/work/extensions/extensions/src/package-extensions.js:148:11)
    at async file:///home/runner/work/extensions/extensions/src/package-extensions.js:119:5

Node.js v20.17.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by jmsdnns** [comment]
To simplify things, the error says to use extension.toml. The one in my theme is right here: https://github.com/jmsdnns/zed-iceicebergy/blob/main/extension.toml

**Comment by maxdeviant** [comment]
> Hmm. From what I can tell, the check didn't fail because of my theme. The log output suggests it is something to do with a package called `kanagawa-themes`.
> 
> ```
> Packaging 'iceicebergy'. Version: 0.3.14
> Checking out Git submodule at 'extensions/iceicebergy'
> 
> Packaging 'kanagawa-themes'. Version: 0.0.1
> Checking out Git submodule at 'extensions/kanagawa-themes'
> file:///home/runner/work/extensions/extensions/src/package-extensions.js:148
>     throw new Error(
>           ^
> 
> Error: The `extension.json` manifest format has been superseded by `extension.toml`
>     at packageExtension (file:///home/runner/work/extensions/extensions/src/package-extensions.js:148:11)
>     at async file:///home/runner/work/extensions/extensions/src/package-extensions.js:119:5
> 
> Node.js v20.17.0
>  ELIFECYCLE  Command failed with exit code 1.
> ```

Your branch needed to be updated with the latest changes from `main`.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
