### PR TITLE
Add Fountain extension

### PR DESCRIPTION
**Pull request by LaPingvino**
I created for now a very basic Fountain extension, based on the documentation I could find and an existing treesitter addon.

### CODE REVIEW

**Comment by LaPingvino** [comment]
(Also very happy for any pointers about how to add outline support)

**Comment by LaPingvino** [comment]
Updated source adding the extension to the extensions.toml file

**Comment by LaPingvino** [comment]
@maxdeviant sorry for the oversight, corrected the issue

**Comment by LaPingvino** [comment]
Now it failed over ember-theme somehow?

**Comment by maxdeviant** [comment]
> Now it failed over ember-theme somehow?

That was due to the branch being out-of-date with `main`.

Now we have this error:

> Error: Extension names should not end with " Zed", as they are all Zed extensions: "Fountain for Zed".

Could you change the extension name to just "Fountain"?

**Comment by LaPingvino** [comment]
> Could you change the extension name to just "Fountain"?

Just done that!

**Review by maxdeviant — APPROVED** [review]
Thank you!

And thanks for being patient through the process 🙂

**Comment by LaPingvino** [comment]
No issue at all! My pleasure!

**Pull request merged**
