### PR TITLE
feat: wgsl grammar extension

### PR DESCRIPTION
**Pull request by luan**

### CODE REVIEW

**Comment by luan** [comment]
@cla-bot check

**Comment by maxbrunsfeld** [comment]
Hey, good to hear from you @luan! Thanks for creating this.

It looks like CI is failing because of a missing `extension.json` at the root of your repo. Here's what that file should look like: https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md#extension-structure.

**Comment by luan** [comment]
Hi @maxbrunsfeld! That's weird, I do have that file in there: https://github.com/luan/zed-wgsl/blob/main/extension.json I'm poking around a bit to see what it could be

**Comment by luan** [comment]
Ah, silly me, I added the submodule incorrectly, just pushed a fix to this branch here.

**Pull request merged**
