### PR TITLE
Add Inform 6 extension

### PR DESCRIPTION
**Pull request by Or4c**
Adds a tree-sitter grammar and syntax highlighting for the Inform 6 programming language for interactive fiction.

### CODE REVIEW

**Comment by Or4c** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@Or4c The URL https://github.com/Or4c/zed-inform6 results in a 404 for me.

Is the repository private?

**Comment by Or4c** [comment]
@maxdeviant Haha why yes it is, forgot to flip that switch, is public now.

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
