### PR TITLE
Add Ember extension

### LINKED ISSUE #193: Handlebars
### Check for existing issues

- [ ] Completed

### Describe the feature

I use for my templates handlebars.js would be nice to have support for that

### If applicable, add mockups / screenshots to help present your vision of the feature

_No response_

### PR DESCRIPTION
**Pull request by jylamont**
This extension starts by adding syntax highlighting for Handlebars/Glimmer files.

Potentially closes #193

### CODE REVIEW

**Comment by jylamont** [comment]
@cla-bot check

**Comment by jylamont** [comment]
Hey @maxdeviant, sorry about this failure, I had forgotten to change the visibility of the repo. It should pull correctly now. Thanks!

**Review by maxdeviant — CHANGES_REQUESTED** [review]
Thanks @jylamont!

Would you mind filling out the `authors` field in the `extension.toml`?

**Comment by jylamont** [comment]
> Would you mind filling out the `authors` field in the `extension.toml`?

No problem @maxdeviant. It should be good to go now. Thanks for taking a look.

**Review by maxdeviant — APPROVED** [review]
Thanks @jylamont!

**Comment by flamestro** [comment]
Hey, thanks for this change, just found it by pure luck while searching for a handlebars extension.

Maybe the description could add the word handlebars so that it can be found in the extension search?

**Comment by notpeter** [comment]
Definitely a good idea, but sadly not enough: 
- https://github.com/zed-industries/zed/issues/10340

**Comment by ferrao** [comment]
> Hey, thanks for this change, just found it by pure luck while searching for a handlebars extension.
> 
> Maybe the description could add the word handlebars so that it can be found in the extension search?

Same here, have been waiting for this, how can anyone guess that to have handlebars support we need to add the Ember extension?

**Pull request merged**
