### PR TITLE
Update Jinja2 to v0.0.2

### PR DESCRIPTION
**Pull request by suraw00t**
Add support a new `.j2` path suffix and bump version for Jinja2

### CODE REVIEW

**Comment by suraw00t** [comment]
@cla-bot check

**Comment by suraw00t** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
We'll also need to update the version to `0.0.2` in the `extension.toml` here:

https://github.com/ArcherHume/jinja2-support/compare/c732da5b9106e0ca6e01a9880c194d37281ebf7e...ef7f82d0c2246d7c00c6f87921a2daf285b9933a#diff-21e42dd2276e594017780607a13f07b058d020447a73c11f032c77823a8ed493R3

**Comment by suraw00t** [comment]
Thanks :smile:

**Comment by SecT0uch** [comment]
@suraw00t Did you close the PR on purpose ?

I would like to use changes from 0.0.2

**Comment by suraw00t** [comment]
I forgot to update this change since that cla-bot check failed, I will reopen this PR.

**Comment by maxdeviant** [comment]
Closing due to inactivity. Please open a new PR once a license has been added to your extension repository.

**Pull request closed without merging**
