### PR TITLE
Add Replicant theme

### PR DESCRIPTION
**Pull request by pierrenel**
Ported one of my favourite [VS Code themes](https://github.com/kenziebottoms/vscode-theme-replicant) over to Zed, so the whole world can use it :) 

preview

### CODE REVIEW

**Comment by pierrenel** [comment]
@cla-bot check

**Comment by pierrenel** [comment]
Do I need to change the .json in the theme directory to a toml file? The examples I looked at had a .json file in the theme directory 🤔

**Comment by notpeter** [comment]
Just switch from extension.json to extension.toml.

See [Developing Extensions](https://zed.dev/docs/extensions/developing-extensions) in the docs for an example.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
