### PR TITLE
Add Ariake theme extension

### PR DESCRIPTION
**Pull request by artivilla**
- Adding dark, light and dawn inspired variations of the Ariake themes

[Preview available](https://github.com/artivilla/zed-ariake-theme)

### CODE REVIEW

**Comment by artivilla** [comment]
@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by artivilla** [comment]
how I can know when this will be available in the next zed release?

**Comment by maxdeviant** [comment]
> how I can know when this will be available in the next zed release?

Extensions aren't tied to the Zed release cycle, so they're available within a few minutes after a PR is merged here:

Screenshot 2024-10-24 at 3 43 01 PM

**Pull request merged**
