### PR TITLE
Add original Material Theme

### PR DESCRIPTION
**Pull request by equinusocio**
Add official Material Theme extension. This is the free version since is not possible to distribute closed-source extensions yet.

Website
https://www.material-theme.dev

Visual Studio Code Marketplace
https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme

GitKraken
https://github.com/material-theme/gitkraken

Others:
https://github.com/material-theme/vsc-material-theme/discussions/1279

### CODE REVIEW

**Comment by maxdeviant** [comment]
> The repository is closed-source as it's a premium extension that requires payment.

We won't be able to distribute an extension on the extension store if it is closed-source.

**Comment by equinusocio** [comment]
Would distributing only the compiled files help?

**Comment by equinusocio** [comment]
> > The repository is closed-source as it's a premium extension that requires payment.
> 
> We won't be able to distribute an extension on the extension store if it is closed-source.

I've updated the repository url to point to our issue-related repository which contains the last compiled version of the theme

**Comment by equinusocio** [comment]
?

**Comment by equinusocio** [comment]
Is any review or changes required?

**Comment by notpeter** [comment]
Hello @equinusocio,

Could you please change id of theme `id` to not include a `.`? Perhaps `material-original` or whatever you prefer.  This should be changed in the following locations:

- extension.toml in your repo
- extensions.toml in this repo
- `extensions/material.theme` submodule directory in this repo
- .gitmodules in this repo

This is because TOML uses dots to signify nested keys so we can't have a theme with `.` in the `id`.  I'll be adding a test to catch this shortly.

**Comment by equinusocio** [comment]
Nope, the extension name is material-theme and this PR is related to https://github.com/zed-industries/extensions/issues/1645

**Comment by OptimusPi** [comment]
Nice work @maxdeviant :) 

p.s. https://www.bleepingcomputer.com/news/security/vscode-extensions-with-9-million-installs-pulled-over-security-risks/amp/?ref=dailydev

**Pull request closed without merging**
