### PR TITLE
Add Pkl extension

### PR DESCRIPTION
**Pull request by Moshyfawn**
I'm fairly new to language configuration, but I decided to give it a try to check out the new experience of creating Zed extensions by adding support for [the Pkl language](https://pkl-lang.org/).

I couldn't quite figure out how to test it locally with Zed, though.

### CODE REVIEW

**Comment by maxdeviant** [comment]
@Moshyfawn Thank you!

**Comment by JosephTLyons** [comment]
This is hilarious! I just began to work on this same plugin up last night! 🤣

**Comment by Moshyfawn** [comment]
> This is hilarious! I just began to work on this same plugin up last night! 🤣

Haha, I was excited to try building an extension for Zed after seeing the announcement post. Coincidentally, I am currently exploring Vim and have been dabbling in Pkl for a possible Terraform configuration. I thought this would be the best combination to spend my time on 🤪

**Comment by Moshyfawn** [comment]
I also got a chuckle out of your Brainfuck PR. I'd never have thought of adding support for it in an IDE 🤭

**Pull request merged**
