### PR TITLE
Add Golangci Lint extension

### PR DESCRIPTION
**Pull request by j4ng5y**
The PR adds a Golangci Lint extension that I added yesterday and should address #525 .

### CODE REVIEW

**Comment by j4ng5y** [comment]
@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by ccoVeille** [comment]
@0xgirish did you find out how to use the extension ?

**Comment by 0xgirish** [comment]
I was able to get it somewhat working. I tried this 2-3 months ago, so I have forgotten the details. 

Here is the patch through which I was able to get diagnostics in zed (at least for a single go file, which I opened first during editor startup) https://github.com/0xgirish/zed_golangci_lint/commit/4dc6d298a522296bbe70d637d16ddd575c9e675b

**Comment by ccoVeille** [comment]
> I was able to get it somewhat working. I tried this 2-3 months ago, so I have forgotten the details. 
> 
> Here is the patch through which I was able to get diagnostics in zed (at least for a single go file, which I opened first during editor startup) https://github.com/0xgirish/zed_golangci_lint/commit/4dc6d298a522296bbe70d637d16ddd575c9e675b

Thanks for your reply @0xgirish 

I posted something in the initial issue about the feature, as for me it's clear the golangci-lint extension cannot be used as-is

- https://github.com/zed-industries/extensions/issues/525#issuecomment-2641111346

Feel free to comment there.

**Pull request merged**
