### PR TITLE
macos-classic 0.0.3

### PR DESCRIPTION
**Pull request by huacnlee**
Release notes:

https://github.com/huacnlee/zed-theme-macos-classic/releases/tag/v0.0.3

> Created by [zed-extension-action](https://github.com/huacnlee/zed-extension-action).

This Pull Request dependency #70, then can work.

### CODE REVIEW

**Comment by huacnlee** [comment]
This just a test by GitHub Action for automatically bump version source repo has been created a new tag.

## GitHub Action:

https://github.com/huacnlee/zed-extension-action

## CI Example

https://github.com/huacnlee/zed-theme-macos-classic/blob/main/.github/workflows/release.yml
https://github.com/huacnlee/zed-theme-macos-classic/actions/runs/7969425850/job/21755218422

image

**Comment by JosephTLyons** [comment]
Hey @huacnlee, can you bump this version number as well?

https://github.com/zed-industries/extensions/blob/92ab1f725aee8e5708429f3b115608e549870f2c/extensions.toml#L47

**Comment by huacnlee** [comment]
I have updated

**Comment by JosephTLyons** [comment]
Thank you!

**Pull request merged**
