### PR TITLE
Add Bend support

### PR DESCRIPTION
**Pull request by mrpedrobraga**
Adding preliminar support for the Bend programming language (with a tree-sitter grammar).
(There's no LS yet).

### CODE REVIEW

**Comment by mrpedrobraga** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
The `grammars` directory in your extension repo should get removed and added to `.gitignore`, as we pull down the grammar when building the extension based on the information in the `extension.toml`.

**Comment by mrpedrobraga** [comment]
It has been done.

**Comment by maxdeviant** [comment]
> It has been done.

The `.gitignore` is there, but the `grammars` directory is still in Git.

It needs to be removed from the repo (e.g., using `git rm`).

**Comment by mrpedrobraga** [comment]
> > It has been done.
> 
> The `.gitignore` is there, but the `grammars` directory is still in Git.
> 
> It needs to be removed from the repo (e.g., using `git rm`).

:sweat_smile: Should be all right now!

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Pull request merged**
