### PR TITLE
Add Grey-theme

### PR DESCRIPTION
**Pull request by mvrcoag**
The Zed Grey Theme is a minimalist and modern light theme designed for developers who prefer a clean and subtle interface. This theme focuses on simplicity and readability, with carefully chosen colors to reduce eye strain while maintaining clarity in your code and interface elements.

### CODE REVIEW

**Comment by mvrcoag** [comment]
@cla-bot check

**Comment by mvrcoag** [comment]
@cla-bot check

**Comment by notpeter** [comment]
Could you please rename your submodule to `grey-theme` instead of `zed-grey-theme` extensions.toml accordingly? We'd like to avoid everything being `extensions/zed-*`

P.S. In the future if you commit your changes to a branch other than `main` on your fork and check the "Allow maintainers to make changes to this branch" we can help fix-up things like this.

**Comment by mvrcoag** [comment]
Thanks for the clarification! The issue has been fixed, and the submodule has been renamed to `grey-theme` as requested. Let me know if there's anything else I can assist you with.

**Comment by notpeter** [comment]
Thanks!

**Pull request merged**
