### PR TITLE
Add Monokai Theme 

### PR DESCRIPTION
**Pull request by billgo**
Adds a theme based on the default monokai pro but with more exciting syntax highlighting.

### CODE REVIEW

**Comment by billgo** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@billgo Could you update the `id` in your extension's `extension.toml` to be lowercase?

https://github.com/billgo/monokai/blob/24a699d2826a604c9b50b248eed00468e34683e4/extension.toml#L1

```diff
- id = "Monokai"
+ id = "monokai"
```

**Comment by billgo** [comment]
> @billgo Could you update the `id` in your extension's `extension.toml` to be lowercase?
> 
> https://github.com/billgo/monokai/blob/24a699d2826a604c9b50b248eed00468e34683e4/extension.toml#L1
> 
> ```diff
> - id = "Monokai"
> + id = "monokai"
> ```

👌 I've already made the modifications.

**Review by maxdeviant — APPROVED** [review]
Thank you!

**Pull request merged**
