### PR TITLE
Add Amber Extension

### PR DESCRIPTION
**Pull request by Ph0enixKM**
# Amber the programming language compiled to Bash

- [Repository of the extension](https://github.com/Ph0enixKM/zed-amber-extension)
- [Repository of the tree sitter](https://github.com/amber-lang/tree-sitter-amber)
- [Repository of the language](https://github.com/amber-lang/amber)
- [Link to the official website](https://amber-lang.com)

Since this is a relatively new programming language, we're still working on LSP and plan to add it's support soon. For now this extension features syntax highlighting with intelligent bracketing.

screenshot

### CODE REVIEW

**Comment by Ph0enixKM** [comment]
@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by maxdeviant** [comment]
> @maxdeviant when will the package be available to download in the zed extensions?

Takes up to ~5 minutes from when CI passes for it to get picked up.

**Comment by Ph0enixKM** [comment]
Thanks @maxdeviant, appreciate your work!

**Pull request merged**
