### PR TITLE
Add typos extension

### PR DESCRIPTION
**Pull request by BaptisteRoseau**
Add support for the [Typos Language Server](https://github.com/tekumara/typos-lsp).

Typos is a spell checker, this extension will help having a bit of spell checking available while waiting for https://github.com/zed-industries/zed/issues/5305

### CODE REVIEW

**Comment by BaptisteRoseau** [comment]
@cla-bot check

**Review by maxdeviant — APPROVED** [review]
Thanks!

**Comment by peteruithoven** [comment]
Would be good to add some Zed specific docs to Typos repo? 
https://github.com/tekumara/typos-lsp?tab=readme-ov-file#install

I'm mostly curious how to configure it using Zed's settings. 
https://github.com/tekumara/typos-lsp/blob/main/docs/vscode-settings.md

**Comment by BaptisteRoseau** [comment]
@peteruithoven  I'll look into it. For now I made a very simple PR just to add the LSP to make it available in the markeplace. I'll add configuration and documentation in the next few days 👍.

**Comment by JosephTLyons** [comment]
Super happy to have this in! I notice that `typos` is very-low positive, and so it doesn't catch as much as I would expect, but anything is an improvement over what we currently have. Happy to see squiggles in my Markdown!

**Pull request merged**
