### PR TITLE
Add move language v0.0.1

### PR DESCRIPTION
**Pull request by Tzal3x**
Closes https://github.com/zed-industries/extensions/issues/717

Here is an example of the LSP working by hovering over the `use sui::dynamic_field as df;`

image

### CODE REVIEW

**Comment by lispking** [comment]
https://github.com/Tzal3x/move-zed-extension/pull/2

@Tzal3x It was found through actual testing that there are some problems with some expressions in the repository. Only after the actual modifications can the grammar display be satisfied. And a pull request (PR) has been submitted to your repository to fix some issues. Please help review it. Thank you.

**Comment by Tzal3x** [comment]
@lispking what are the issues? I am not able to install the extension using the modifications you submitted. 

The PR I submitted is functional, so this can be merged. We can make patch to the extension (if needed) when the exact problem is highlighted. Thanks! 🚀

**Comment by lispking** [comment]
Alternatively, I'll submit the patch to your repository. That would be more appropriate. @Tzal3x

**Comment by Tzal3x** [comment]
Just saw your update on the PR @lispking. Nice work, merged! ✅ 

Let's hope zed maintainers will accept this one soon to reach the community.

**Comment by Tzal3x** [comment]
Hey, @notpeter respectively asking for your review. 🙏

**Comment by notpeter** [comment]
I know this is a big ask, but would be willing to re-write history for your repo to remove the 60-odd MB of binaries from /target which were accidentally included in-tree prior to https://github.com/Tzal3x/move-zed-extension/commit/d49f35fab5fb63fcb04ca8f7f970654366d8cfcf?

I know it's a PITA, but I would prefer not require another 60MB of disk storage on everyone who recursively checks out the extensions repo.  I'd recommend something like [git-filter-repo](https://github.com/newren/git-filter-repo/blob/main/INSTALL.md).  Here's an example git-filter-repo usage instructions we use [extracting extensions from the zed repo](https://github.com/zed-industries/zed/blob/ee3869393707bf8e7623eb0369f2e2963c7fe89a/extensions/EXTRACTION.md?plain=1).

The [zed repo](https://github.com/zed-industries/zed) submodule is by far the worst offender (192MB) but we are working to remove that entirely in favor of individual extension repos.

**Comment by Tzal3x** [comment]
That would be a huge PITA indeed, and since this is the very first version of the extension I just squashed all commits. From now on each patch/version will have its own commit and it's done. Good ol' `git rebase -I`.

**Comment by notpeter** [comment]
I [bumped the submodule commit](https://github.com/zed-industries/extensions/commit/05dff1340308394c908e8112f1ea732fc3b8b7bc.patch) on your branch.

1. 176KB is much better than 60MB.

2. This change broke tests, I think because you have queries which reference a newer release of the tree-sitter than what is referenced in [extensions.toml](https://github.com/Tzal3x/move-zed-extension/blob/99a2923283ea3352342fb73da0b1ba98c09682c0/extension.toml#L16-L18)

A lot has happened since `8bc0d1692caa8763fef54d48068238d9bf3c0264`
Compare: https://github.com/tzakian/tree-sitter-move/compare/8bc0d1692caa8763fef54d48068238d9bf3c0264...main

3. You should actually .gitignore `grammars/` directory altogether too.

**Comment by Tzal3x** [comment]
I see that the CI is failing. Is there something I can do on the extension's side? I can't understand the error.

**Comment by Tzal3x** [comment]
Awesome! The `grammars/` are already included in the `.gitignore` so that's fine. 

Ok so I bumped up the version of the tree-sitter to the latest commit `f5b37f63569f69dfbe7a9950527786d2f6b1d35c`. 

Can you retry running the CI please?

**Comment by Tzal3x** [comment]
I'm not sure I understand the error of the CI, and I don't have access re-running it to experiment with it. Mind lending a hand here? 😬

**Comment by notpeter** [comment]
That did it! Thanks! And congrats on your first Zed Extension!

**Pull request merged**
