### PR TITLE
Update monosami to v0.1.1

### PR DESCRIPTION
**Pull request by borngraced**
fix: light theme ghost element selected contrast

### CODE REVIEW

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@borngraced We now require that extensions use the `extension.toml` manifest format instead of `extension.json`.

Would you mind updating your extension to use `extension.toml`?

**Comment by borngraced** [comment]
done

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@borngraced It looks like the ID in `extension.toml` changed.

We'll want to keep it as `monosami`.

**Comment by borngraced** [comment]
??

**Comment by maxdeviant** [comment]
> ??

I didn't know you had made the change, since the submodule was never updated in this PR.

It looks like the version in `extension.toml` still needs to be updated to `0.1.1`: https://github.com/borngraced/monosami/blob/7527efaf622234c8f4fbd8ec5afe7cc8481f6dc3/extension.toml#L3

**Comment by borngraced** [comment]
> > ??
> 
> I didn't know you had made the change, since the submodule was never updated in this PR.
> 
> It looks like the version in `extension.toml` still needs to be updated to `0.1.1`: https://github.com/borngraced/monosami/blob/7527efaf622234c8f4fbd8ec5afe7cc8481f6dc3/extension.toml#L3

ah okay got it..

**Review by maxdeviant — APPROVED** [review]

**Pull request merged**
