### PR TITLE
Add Anya Theme

### PR DESCRIPTION
**Pull request by choednwn**

### CODE REVIEW

**Comment by choednwn** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
@choednwn It looks like the repo for your extension is not public.

I get a 404 when trying to visit https://github.com/anya-theme/anya-zed.

**Comment by choednwn** [comment]
@maxdeviant Oops. I didn't notice that. I have changed the repo to public.

**Review by maxdeviant — APPROVED** [review]
@choednwn Thanks!

**Pull request merged**
