### PR TITLE
Update `catppuccin` theme

### PR DESCRIPTION
**Pull request by ssaunderss**
Updated the git submodule after finishing porting / polishing the rest of the catppuccin themes.

### CODE REVIEW

**Review by ssaunderss — COMMENTED** [review]
revert version update

**Comment by ssaunderss** [comment]
@JosephTLyons @maxdeviant I reverted the version bump and it looks like the CICD is passing now. What's the process for versioning extensions?

**Comment by maxdeviant** [comment]
@ssaunderss Hmm, you should just need to bump the version in `extensions.toml` and in the `extension.json` in the theme repository.

**Comment by ssaunderss** [comment]
@maxdeviant that was it, thanks!

**Pull request merged**
