### PR TITLE
Bump Solidity to 0.0.3

### PR DESCRIPTION
**Pull request by zarifpour**
[🫂 Support more keywords](https://github.com/zarifpour/zed-solidity/commit/1394052dc02c131f120c94ca5426b065559bf8f4)

### CODE REVIEW

**Comment by maxdeviant** [comment]
Is the removal of the Tree-sitter grammar from the extension repo intentional?

**Comment by zarifpour** [comment]
> Is the removal of the Tree-sitter grammar from the extension repo intentional?

No, thank you for the review!

**Comment by zarifpour** [comment]
This is not the first time this has happened after testing, have you considered allowing the `.toml` to exist alongside the `.wasm` for testing? I keep having to delete it to get the language to load.

**Comment by zarifpour** [comment]
Perhaps something could be added to the extension CI?

**Comment by maxdeviant** [comment]
> Perhaps something could be added to the extension CI?

We are going to improve the extension CI at some point to do more validation of language extensions.

**Comment by zarifpour** [comment]
I noticed Zed hasn't detected the update yet, has something changed in the release cycle?
CleanShot 2024-03-12 at 14 42 37 on Zed — 21cli

**Comment by maxdeviant** [comment]
> I noticed Zed hasn't detected the update yet, has something changed in the release cycle? CleanShot 2024-03-12 at 14 42 37 on Zed — 21cli

Hmm, the CI seems to have run fine, but I'm not seeing the new version either 🤔

**Comment by maxdeviant** [comment]
@zarifpour We tracked it down to another extension with a malformed manifest that was preventing other extensions from being updated.

The new version of Solidity is available now.

**Pull request merged**
