### PR TITLE
Add dockerignore extension

### PR DESCRIPTION
**Pull request by eth0net**
This PR brings a new extension to support syntax highlighting for `.dockerignore` files.

### CODE REVIEW

**Comment by d1y** [comment]
I think it would be better if the dockerignore syntax highlighting could be put here https://github.com/d1y/dockerfile.zed
:)

**Comment by eth0net** [comment]
> I think it would be better if the dockerignore syntax highlighting could be put here https://github.com/d1y/dockerfile.zed :)

I also have a Docker Compose extension, would be better to combine them all but I originally avoided adding to your dockerfile extension since ideally it would be a new `Docker` extension. I had also forgotten about dockerignore at the time or I'd have just started on the combined one then 🤦🏻‍♀️

**Comment by maxdeviant** [comment]
@eth0net Did you still want to publish this extension now that `git-firefly` supports `.dockerignore`?

**Comment by eth0net** [comment]
Perhaps not, it might be worth condensing it into a whole docker extension at some point but for now let's close this.

**Pull request closed without merging**
