### PR TITLE
Add rainbow-csv extension

### PR DESCRIPTION
**Pull request by weartist**
Add a csv extension to solve: #475 

it look like:
image

At the same time, the tsv extension has been added, They may be merged into the same extension in the future,and I will refine the logic of automatic indentation alignment in the future

### CODE REVIEW

**Comment by huacnlee** [comment]
Hi @weartist you can add this support in csv extension.

https://github.com/huacnlee/zed-csv

I was created that extension last week, but your version is better for display.

We can to merge your version in to that, and you are the member or zed-csv to maintain it.

**Comment by weartist** [comment]
> Hi @weartist you can add this support in csv extension.
> 
> https://github.com/huacnlee/zed-csv
> 
> I was created that extension last week, but your version is better for display.
> 
> We can to merge your version in to that, and you are the member or zed-csv to maintain it.

I looked at your extension, but because we need to separate the different colors by columns, we need a special tree-sitter match, maybe we can coexist

**Comment by huacnlee** [comment]
I mean, if you want, you can:

1. Just use `csv` extension name (If you choose this, just rename your extension name and remove old info.). 
2. Or merge your code into the same project if you like.

I can do both.

Then there is only have 1 CSV extension for Zed.
You're doing is better than I did.

**Comment by weartist** [comment]
> I mean, if you want, you can:
> 
> 1. Just use `csv` extension name (If you choose this, just rename your extension name and remove old info.).
> 2. Or merge your code into the same project if you like.
> 
> I can do both.
> 
> Then there is only have 1 CSV extension for Zed. You're doing is better than I did. Because I will be going to use your version instead of old one when you release. So maybe the old one is useless now.



> I mean, if you want, you can:
> 
> 1. Just use `csv` extension name (If you choose this, just rename your extension name and remove old info.).
> 2. Or merge your code into the same project if you like.
> 
> I can do both.
> 
> Then there is only have 1 CSV extension for Zed. You're doing is better than I did. Because I will be going to use your version instead of old one when you release. So maybe the old one is useless now.

Yes, maybe that's a better way to keep one, and I'm also considering if I could combine csv and tsv into one extension

**Comment by huacnlee** [comment]
Here is an example of 1 Zed extension including 2 languages support.

https://github.com/navi-language/zed-navi

I have done a search, looks like TSV is a part of the CSV?

If that right, I think we can include them and use `CSV` as the extension name.

**Comment by weartist** [comment]
> Here is an example of 1 Zed extension including 2 languages support.
> 
> https://github.com/navi-language/zed-navi
> 
> I have done a search, looks like TSV is a part of the CSV?
> 
> If that right, I think we can include them and use `CSV` as the extension name.

 yes, I also looked at some of the code and found out putting both of them in one extension is currently possible, I made some modifications and it is currently compatible with both formats

**Comment by weartist** [comment]
@maxdeviant hi, I wonder if the extension qualifies, and I'll continue to think about the logic of the indentation if I can

**Comment by maxdeviant** [comment]
> @maxdeviant hi, I wonder if the extension qualifies, and I'll continue to think about the logic of the indentation if I can

Yea, I'd be happy to merge this one.

Could you remove the Rust crate in the extension, since it doesn't appear to be used?

https://github.com/weartist/zed-rainbow-csv/blob/d4075700728d68d2292c7ee7c1b5d88330f57e09/src/lib.rs

So no `Cargo.toml` or `src/` directory.

**Comment by JosephTLyons** [comment]
This is looking 🔥!

**Comment by weartist** [comment]
> > @maxdeviant hi, I wonder if the extension qualifies, and I'll continue to think about the logic of the indentation if I can
> 
> Yea, I'd be happy to merge this one.
> 
> Could you remove the Rust crate in the extension, since it doesn't appear to be used?
> 
> https://github.com/weartist/zed-rainbow-csv/blob/d4075700728d68d2292c7ee7c1b5d88330f57e09/src/lib.rs
> 
> So no `Cargo.toml` or `src/` directory.

I misunderstood this, I thought we needed to keep it there, thanks for the reminder

**Comment by JosephTLyons** [comment]
The crate is optional, only if you are adding language server support would you need it. Also, really excited to use this extension in a blog post Im doing! 😂

**Comment by maxdeviant** [comment]
@weartist I think we're almost there.

We need to remove the `Cargo.toml` from the extension repository, as otherwise the extension builder thinks there's a Rust crate it needs to build: https://github.com/weartist/zed-rainbow-csv/blob/0cc3fa8360a8549f1744c67349fe5b6aaab3dd43/Cargo.toml

**Comment by weartist** [comment]
> @weartist I think we're almost there.
> 
> We need to remove the `Cargo.toml` from the extension repository, as otherwise the extension builder thinks there's a Rust crate it needs to build: https://github.com/weartist/zed-rainbow-csv/blob/0cc3fa8360a8549f1744c67349fe5b6aaab3dd43/Cargo.toml


Handled, sorry for my previous misunderstanding

**Comment by maxdeviant** [comment]
@weartist Thanks, this looks cool!

**Comment by JosephTLyons** [comment]
Very cool! The example in my Markdown file! Going to tweet this extension out tomorrow, if there isn't anything big lined up.

SCR-20240425-tznu

**Pull request merged**
