### PR TITLE
Add swift-lsp

### PR DESCRIPTION
**Pull request by ejjonny**

### CODE REVIEW

**Review by marcusziade — APPROVED** [review]
Read through the implementation 
https://github.com/ejjonny/swift-ext.git

lgtm

**Comment by furby-tm** [comment]
Before this goes in @ejjonny could we get this [PR](https://github.com/ejjonny/swift-ext/pull/4) in for a much needed improvement on the Syntax highlighting for Swift?

**Comment by WeetHet** [comment]
Hi, thanks for the incredible work! As far as I know, it might be better to make this a pull request to https://github.com/zed-extensions/swift/ or ever ask @maxdeviant for write access to that repository. Do we really need two extensions right now, one of which would work and one wouldn't? This would only confuse people

**Comment by ejjonny** [comment]
Sure, WIP here https://github.com/zed-extensions/swift/pull/6 something is broken though after transferring things to the new repo - I'll look into it sometime soon.

**Comment by furby-tm** [comment]
@ejjonny Ah nice, if you use that repo, my **PR** should be unnecessary because I believe that `highlights.scm` is identical to my [**PR](https://github.com/ejjonny/swift-ext/pull/4).

**Pull request closed without merging**
