### PR TITLE
Add Kanagawa theme extension

### PR DESCRIPTION
**Pull request by IYair**
## Summary

This PR introduces the Kanagawa theme for Zed with three unique variants:
- **Wave**: A calm dark theme with cool blue and green tones
- **Dragon**: A vibrant dark theme featuring deep reds and rich greens
- **Lotus**: A light theme with soft, warm pastel colors

## Changes

- Added three theme JSON files for each variant
- Ensured terminal colors match the overall theme aesthetic
- Included README with detailed installation and usage instructions

## How to Test

1. Clone the repository and navigate to the extension directory.
2. Install the extension locally using the Zed CLI: `zed install path/to/extension`.
3. Apply each theme variant in Zed settings and verify the color consistency across different UI elements and syntax highlighting.

## Repository
https://github.com/IYair/kanagawa-theme.git

## Feedback

All feedback is welcome! Please let me know if there are any additional features or improvements you would like to see.

---

Thank you for reviewing this PR!

### CODE REVIEW

**Comment by IYair** [comment]
@cla-bot check

**Review by maxdeviant — CHANGES_REQUESTED** [review]
It looks like we already have a `kanagawa-themes` extension in the repo.

We don't want to have two extensions with such similar names.

**Comment by IYair** [comment]
I had not noticed, although I understand that they do not want to have two extensions with the same name, I think my theme brings a lot of value to have more variety.

**Comment by maxdeviant** [comment]
> I had not noticed, although I understand that they do not want to have two extensions with the same name, I think my theme brings a lot of value to have more variety.

There are a few options here:

1. If your theme and the other Kanagawa theme are both based on some existing theme (e.g., from another editor), then you could see about contributing the changes to the existing theme.
2. If this is a brand new theme that is unrelated to the existing Kanagawa theme, then you could consider choosing a different name.

**Comment by IYair** [comment]
Convert this PR to a draft pending the outcome of ethangilmore/zed-kanagawa#2

**Pull request closed without merging**
