### PR TITLE
Update sql extension

### PR DESCRIPTION
**Pull request by evrsen**
- [x] (https://github.com/evrsen/zed-sql/pull/1) Fixed line comments not being highlighted properly
- [x] (https://github.com/zed-industries/extensions/pull/418#issuecomment-2029861012) Fixed previous issue where a git submodule was accidentally included
- [ ] Support for prettier formatting
- [ ] Integrate LSP support to the extension

### CODE REVIEW

**Comment by evrsen** [comment]
My email is set up, what is wrong here?

**Comment by maxdeviant** [comment]
> My email is set up, what is wrong here?

These old commits appear to have the wrong author attribution on them:

Screenshot 2024-04-12 at 7 38 09 AM

**Comment by evrsen** [comment]
Thanks for reaching out! Sorry, I don't know how to fix this

**Comment by evrsen** [comment]
Sorry, i give up on this, having very difficult times trying to fix this.

**Pull request closed without merging**
