### PR TITLE
Add everforest theme

### PR DESCRIPTION
**Pull request by ThomasAlban**
image

Currently I've only ported the dark version!

### CODE REVIEW

**Comment by ThomasAlban** [comment]
@cla-bot check

**Comment by maxdeviant** [comment]
@ThomasAlban Thank you!

**Comment by ThomasAlban** [comment]
> Excuse my ignorance but is this theme going to be in the marketplace or a default theme?

You can search for it in Zed extensions and it's there, it's not a default theme but an extension!

**Comment by fuzenco** [comment]
Whoa! I didn’t know the Extensions menu item existed. Mind blown. Installed and happy. Thanks.

**Pull request merged**
